export type BlogCategory =
  | 'revenus'
  | 'visibilite'
  | 'experience'
  | 'ressources'
  | 'automatisation'
  | 'reglementation'
  | 'conciergerie'
  | 'fiscalite'
  | 'driing'

export interface BlogArticle {
  slug: string
  categorySlug: BlogCategory
  date: string
  readTime: number
  title: string
}

export const BLOG_CATEGORIES: Record<BlogCategory, { label: string; color: string; bg: string }> = {
  revenus:        { label: 'Revenus',         color: '#B06010', bg: 'rgba(176,96,16,.1)'  },
  visibilite:     { label: 'Visibilité',      color: '#004C3F', bg: 'rgba(0,76,63,.1)'    },
  experience:     { label: 'Expérience',      color: '#92400E', bg: 'rgba(146,64,14,.1)'  },
  ressources:     { label: 'Ressources',      color: '#6D28D9', bg: 'rgba(109,40,217,.1)' },
  automatisation: { label: 'Automatisation',  color: '#2563EB', bg: 'rgba(37,99,235,.1)'  },
  reglementation: { label: 'Réglementation',  color: '#991B1B', bg: 'rgba(153,27,27,.1)'  },
  conciergerie:   { label: 'Conciergerie',    color: '#003329', bg: 'rgba(0,51,41,.1)'    },
  fiscalite:      { label: 'Fiscalité',       color: '#556B2F', bg: 'rgba(85,107,47,.1)'  },
  driing:         { label: 'Driing',          color: '#003329', bg: 'rgba(255,213,107,.18)' },
}

export const BLOG_ARTICLES: BlogArticle[] = [
  { slug: 'optimiser-annonce-airbnb', categorySlug: 'visibilite', date: '2025-03-01', readTime: 5, title: 'Optimiser son annonce Airbnb : les 8 éléments qui font vraiment la différence' },
  { slug: 'tarification-dynamique-lcd', categorySlug: 'revenus', date: '2025-03-01', readTime: 7, title: 'Tarification dynamique en location courte durée : par où commencer' },
  { slug: 'messages-airbnb-automatiser', categorySlug: 'automatisation', date: '2025-03-01', readTime: 4, title: 'Les 5 messages Airbnb à automatiser absolument dès cette semaine' },
  { slug: 'google-my-business-hotes-lcd', categorySlug: 'visibilite', date: '2025-03-01', readTime: 6, title: 'Pourquoi Google My Business est indispensable pour les hôtes LCD en 2025' },
  { slug: 'reservation-directe-sans-commission', categorySlug: 'revenus', date: '2025-03-01', readTime: 8, title: 'Réservation directe sans commission : comment se lancer sans site web' },
  { slug: 'creer-conciergerie-airbnb-2025', categorySlug: 'conciergerie', date: '2025-03-01', readTime: 10, title: 'Créer sa conciergerie Airbnb en 2025 : les étapes essentielles pour démarrer' },
  { slug: 'obtenir-avis-5-etoiles-airbnb', categorySlug: 'experience', date: '2025-03-01', readTime: 5, title: 'Comment obtenir plus d\'avis 5 étoiles sur Airbnb sans harceler tes voyageurs' },
  { slug: 'location-courte-duree-impots-france', categorySlug: 'fiscalite', date: '2025-03-01', readTime: 9, title: 'Location courte durée et impôts : ce que tout hôte doit savoir en France' },
  { slug: 'outils-gerer-location-courte-duree-2025', categorySlug: 'automatisation', date: '2025-03-01', readTime: 6, title: 'Les 7 outils indispensables pour gérer sa location courte durée en 2025' },
  { slug: 'livret-accueil-digital-hotes-lcd', categorySlug: 'experience', date: '2025-03-01', readTime: 4, title: 'Livret d\'accueil digital : pourquoi c\'est devenu indispensable pour les hôtes LCD' },
  { slug: 'reglementation-lcd-france-2026', categorySlug: 'reglementation', date: '2025-11-01', readTime: 8, title: 'Réglementation LCD France 2026 : tout ce qui change pour les hôtes' },
  { slug: 'driing-plateforme-vacances-sans-commissions', categorySlug: 'driing', date: '2025-03-01', readTime: 6, title: 'Driing : la plateforme de vacances sans commissions qui change la donne' },
  { slug: 'airbnb-vs-booking-com-location-courte-duree', categorySlug: 'visibilite', date: '2026-03-25', readTime: 8, title: 'Airbnb vs Booking.com : lequel choisir pour ton logement LCD ?' },
  { slug: 'photographier-logement-location-courte-duree-smartphone', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Comment photographier son logement LCD soi-même (sans matériel pro)' },
  { slug: 'attirer-teletravailleur-nomade-digital-location-courte-duree', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Télétravail et LCD : comment attirer les nomades digitaux dans ton logement' },
  { slug: 'gerer-mauvais-avis-airbnb-reponse-hote', categorySlug: 'experience', date: '2026-03-25', readTime: 6, title: 'Comment gérer un mauvais avis sur Airbnb sans perdre ton classement' },
  { slug: 'declarer-activite-location-courte-duree-france-demarches', categorySlug: 'reglementation', date: '2026-03-25', readTime: 9, title: 'Déclarer son activité LCD en France : les démarches administratives à connaître' },
  { slug: 'gerer-voyageurs-difficiles-location-courte-duree', categorySlug: 'experience', date: '2026-03-25', readTime: 7, title: 'Voyageurs difficiles en LCD : comment prévenir et gérer les situations problématiques' },
  { slug: 'site-reservation-directe-location-courte-duree', categorySlug: 'revenus', date: '2026-03-25', readTime: 8, title: 'Créer son premier site de réservation directe en LCD : par où commencer' },
  { slug: 'conciergerie-airbnb-faire-appel-choisir', categorySlug: 'conciergerie', date: '2026-03-25', readTime: 7, title: 'Conciergerie Airbnb : faut-il en faire appel à une et comment bien la choisir ?' },
  { slug: 'titre-annonce-airbnb-optimiser-clics-visibilite', categorySlug: 'visibilite', date: '2026-03-25', readTime: 6, title: 'Titre d\'annonce Airbnb : comment écrire un titre qui fait cliquer' },
  { slug: 'tarification-dynamique-pricelabs-wheelhouse-beyond-comparatif', categorySlug: 'revenus', date: '2026-03-25', readTime: 8, title: 'Tarification dynamique en LCD : Pricelabs, Wheelhouse ou Beyond — lequel choisir ?' },
  { slug: 'livret-accueil-digital-creer-location-courte-duree', categorySlug: 'experience', date: '2026-03-25', readTime: 7, title: 'Livret d\'accueil digital : pourquoi c\'est devenu indispensable et comment en créer un' },
  { slug: 'fixer-prix-minimum-airbnb-lcd', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Comment fixer son prix minimum sur Airbnb sans se brader' },
  { slug: 'erreurs-debutant-location-courte-duree-premier-logement', categorySlug: 'revenus', date: '2026-03-25', readTime: 9, title: 'Premier logement LCD : les 10 erreurs à éviter quand on se lance' },
  { slug: 'location-directe-pourquoi-saffranchir-plateformes', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Location en direct : pourquoi de plus en plus d\'hôtes s\'affranchissent des plateformes' },
  { slug: 'premieres-reservations-directes-sans-audience-site-web', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Comment obtenir ses premières réservations directes sans audience ni site web' },
  { slug: 'base-voyageurs-fideles-location-directe-durable', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Construire une base de voyageurs fidèles : la clé de la location directe durable' },
  { slug: 'fixer-prix-reservation-directe-location-courte-duree', categorySlug: 'revenus', date: '2026-03-25', readTime: 6, title: 'Comment fixer son prix pour la réservation directe : ni trop cher, ni bradé' },
  { slug: 'securiser-paiement-reservation-directe-sans-airbnb', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Réservation directe : comment sécuriser le paiement et protéger ton logement sans Airbnb' },
  { slug: 'instagram-hotes-lcd-attirer-voyageurs-reservations-directes', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Instagram pour hôtes LCD : comment attirer des voyageurs directement depuis les réseaux' },
  { slug: 'politique-annulation-location-directe-hote', categorySlug: 'revenus', date: '2026-03-25', readTime: 6, title: 'Gérer les annulations en location directe : quelle politique adopter et comment l\'appliquer' },
  { slug: 'description-logement-convertit-reservation-directe', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Rédiger une description de logement qui convertit en réservation directe' },
  { slug: 'google-my-business-reservations-directes-hotes-lcd', categorySlug: 'visibilite', date: '2026-03-25', readTime: 8, title: 'Google My Business pour hôtes LCD : le levier gratuit qui génère des réservations directes' },
  { slug: 'pms-logiciel-gestion-location-courte-duree-debutant', categorySlug: 'automatisation', date: '2026-03-25', readTime: 8, title: 'PMS pour débutant : quel logiciel choisir selon ton profil LCD ?' },
  { slug: 'mesurer-performance-canal-reservation-directe-kpi', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Mesurer la performance de ton canal de réservation directe : les chiffres qui comptent vraiment' },
  { slug: 'verification-voyageurs-avant-accepter-reservation-lcd', categorySlug: 'experience', date: '2026-03-25', readTime: 6, title: 'Comment vérifier un voyageur avant d\'accepter sa réservation en LCD' },
  { slug: 'gabarits-messages-lcd-hotes-templates', categorySlug: 'automatisation', date: '2026-03-25', readTime: 5, title: 'Gabarits de messages LCD : arrête de réécrire les mêmes messages à chaque voyageur' },
  { slug: 'communaute-lcd-groupes-hotes-entraide-facebook', categorySlug: 'ressources', date: '2026-03-25', readTime: 6, title: 'Communauté LCD : pourquoi les meilleurs hôtes ne travaillent pas seuls' },
  { slug: 'partenaires-lcd-outils-valides-terrain-hotes', categorySlug: 'ressources', date: '2026-03-25', readTime: 6, title: 'Partenaires LCD : pourquoi les outils que tu utilises méritent d\'être validés avant d\'y mettre ton argent' },
  { slug: 'formation-google-my-business-lcd-contenu', categorySlug: 'visibilite', date: '2026-03-25', readTime: 5, title: 'Formation Google My Business pour la LCD : ce qu\'elle contient et pourquoi la suivre' },
  { slug: 'chambres-hotes-plateforme-jason-marinho-ressources', categorySlug: 'ressources', date: '2026-03-25', readTime: 6, title: 'Chambres d\'hôtes : comment la plateforme Jason Marinho t\'aide à développer ton activité' },
  { slug: 'conciergeries-lcd-ressources-plateforme-jason-marinho', categorySlug: 'conciergerie', date: '2026-03-25', readTime: 6, title: 'Conciergeries LCD : les ressources de la plateforme qui font gagner du temps à grande échelle' },
  { slug: 'formations-lcd-disponibles-plateforme-jason-marinho', categorySlug: 'ressources', date: '2026-03-25', readTime: 5, title: 'Formations LCD disponibles sur la plateforme : ce que tu peux suivre maintenant et ce qui arrive' },
  { slug: 'pourquoi-creer-compte-plateforme-jason-marinho', categorySlug: 'ressources', date: '2026-03-25', readTime: 5, title: 'Pourquoi créer un compte gratuit sur la plateforme Jason Marinho dès maintenant' },
  { slug: 'checklist-menage-professionnelle-location-courte-duree', categorySlug: 'experience', date: '2026-03-25', readTime: 6, title: 'Checklist ménage professionnelle pour hôte LCD (+ gabarit à télécharger)' },
  { slug: 'appel-decouverte-jason-marinho-accompagnement-lcd', categorySlug: 'ressources', date: '2026-03-25', readTime: 5, title: 'L\'appel découverte Jason Marinho : à qui ça s\'adresse et ce qu\'on y fait en 30 minutes' },
  { slug: 'assurance-location-courte-duree-airbnb-couverture', categorySlug: 'reglementation', date: '2026-03-25', readTime: 8, title: 'Assurance location courte durée : ce qu\'Airbnb couvre vraiment (et ce qu\'il ne couvre pas)' },
  { slug: 'bail-mobilite-vs-courte-duree-differences', categorySlug: 'reglementation', date: '2026-03-25', readTime: 7, title: 'Bail mobilité vs location courte durée : ce que chaque hôte doit comprendre' },
  { slug: 'airdna-mode-emploi-hote-lcd-debutant', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'AirDNA : mode d\'emploi pour l\'hôte LCD débutant qui veut des données fiables' },
  { slug: 'algorithme-airbnb-2026-criteres-classement', categorySlug: 'visibilite', date: '2026-03-25', readTime: 8, title: 'Algorithme Airbnb 2026 : les 7 critères de classement que tout hôte doit connaître' },
  { slug: 'amenager-logement-location-courte-duree-petit-budget', categorySlug: 'experience', date: '2026-03-25', readTime: 8, title: 'Aménager son logement LCD avec un petit budget : 12 idées testées sur le terrain' },
  { slug: 'automatiser-caution-swikly-youka-test-terrain', categorySlug: 'automatisation', date: '2026-03-25', readTime: 6, title: 'Automatiser la caution LCD : Swikly, Youka, test terrain — lequel choisir ?' },
  { slug: 'basse-saison-location-courte-duree-strategies-reservations', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Basse saison LCD : 8 stratégies concrètes pour maintenir ses réservations' },
  { slug: 'blog-hote-lcd-strategie-trafic-organique', categorySlug: 'visibilite', date: '2026-03-25', readTime: 6, title: 'Créer un blog pour hôte LCD : pourquoi et comment générer du trafic organique gratuit' },
  { slug: 'booking-com-hotes-location-courte-duree-guide', categorySlug: 'visibilite', date: '2026-03-25', readTime: 8, title: 'Booking.com pour hôtes LCD : guide complet pour s\'inscrire et maximiser ses réservations' },
  { slug: 'bruit-reglement-interieur-lcd-efficace', categorySlug: 'experience', date: '2026-03-25', readTime: 5, title: 'Bruit et nuisances en LCD : comment rédiger un règlement intérieur vraiment efficace' },
  { slug: 'accueillir-famille-enfants-airbnb-equipement', categorySlug: 'experience', date: '2026-03-25', readTime: 5, title: 'Accueillir des familles avec enfants en LCD : équipements et astuces pour 5 étoiles' },
  { slug: 'accueillir-voyageur-business-lcd-essentiels', categorySlug: 'experience', date: '2026-03-25', readTime: 5, title: 'Accueillir des voyageurs business en LCD : les 10 essentiels qui font la différence' },
  { slug: 'assurance-lcd-5-garanties-indispensables-2026', categorySlug: 'reglementation', date: '2026-04-25', readTime: 7, title: '5 garanties indispensables pour ton assurance LCD en 2026' },
  { slug: 'base-voyageurs-fideles-location-directe-durable', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Construire une base de voyageurs fidèles pour la location directe durable' },
  { slug: 'check-in-autonome-boite-cles-serrure-connectee-lcd', categorySlug: 'automatisation', date: '2026-03-25', readTime: 6, title: 'Check-in autonome en LCD : boîte à clés ou serrure connectée — lequel choisir ?' },
  { slug: 'check-in-automatique-hotes-lcd-guide', categorySlug: 'automatisation', date: '2026-04-25', readTime: 6, title: 'Check-in automatique pour hôtes LCD : guide complet pour se libérer du check-in manuel' },
  { slug: 'channel-manager-lcd-comparatif', categorySlug: 'automatisation', date: '2026-04-25', readTime: 8, title: 'Channel manager LCD : comparatif des 5 meilleurs pour hôtes indépendants' },
  { slug: 'conciergerie-airbnb-creer-service-pro', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 8, title: 'Conciergerie Airbnb : comment créer un service professionnel qui se vend' },
  { slug: 'contrat-location-directe-mentions-obligatoires', categorySlug: 'reglementation', date: '2026-04-25', readTime: 7, title: 'Contrat de location directe : les mentions obligatoires et comment le rédiger' },
  { slug: 'declarer-meuble-tourisme-mairie-formalites', categorySlug: 'reglementation', date: '2026-04-25', readTime: 8, title: 'Déclarer son meublé de tourisme en mairie : formalités étape par étape' },
  { slug: 'eco-responsable-lcd-conseils-hotes', categorySlug: 'experience', date: '2026-04-25', readTime: 6, title: 'LCD éco-responsable : 10 actions concrètes pour séduire les voyageurs green' },
  { slug: 'fiscalite-location-meublee-lmnp-lmp-2026', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 10, title: 'Fiscalité location meublée LMNP vs LMP en 2026 : guide complet pour hôtes' },
  { slug: 'gestion-co-hotes-airbnb-guide', categorySlug: 'automatisation', date: '2026-04-25', readTime: 6, title: 'Co-hôtes sur Airbnb : comment les gérer et déléguer efficacement' },
  { slug: 'guide-complet-hote-airbnb-debutant-2026', categorySlug: 'revenus', date: '2026-04-25', readTime: 12, title: 'Guide complet de l\'hôte Airbnb débutant en 2026 : tout ce qu\'il faut savoir avant de se lancer' },
  { slug: 'hausse-loyers-lcd-zones-tendues-2026', categorySlug: 'reglementation', date: '2026-04-25', readTime: 7, title: 'Zones tendues et LCD : ce que la réglementation 2026 change concrètement' },
  { slug: 'home-staging-low-cost-airbnb-budget', categorySlug: 'experience', date: '2026-04-25', readTime: 7, title: 'Home staging low-cost pour Airbnb : transformer son logement LCD pour 300 €' },
  { slug: 'location-courte-duree-meublee-tourisme-differences', categorySlug: 'reglementation', date: '2026-04-25', readTime: 7, title: 'LCD vs meublé de tourisme : quelles différences et quel statut choisir ?' },
  { slug: 'mentions-legales-site-reservation-directe', categorySlug: 'reglementation', date: '2026-04-25', readTime: 6, title: 'Mentions légales pour site de réservation directe : ce qu\'il faut publier' },
  { slug: 'micro-bic-abattement-2026-airbnb', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 10, title: 'Abattement micro-BIC 2026 : ce que la loi Le Meur coûte vraiment aux hôtes Airbnb' },
  { slug: 'optimiser-taux-occupation-lcd-strategies', categorySlug: 'revenus', date: '2026-04-25', readTime: 7, title: 'Taux d\'occupation LCD : 9 leviers concrets pour l\'optimiser toute l\'année' },
  { slug: 'photos-avant-apres-home-staging-lcd', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Photos avant-après home staging LCD : 5 transformations à 200 €' },
  { slug: 'pricelabs-guide-complet-hotes-lcd', categorySlug: 'revenus', date: '2026-04-25', readTime: 8, title: 'PriceLabs : guide complet pour hôtes LCD qui veulent maîtriser la tarification dynamique' },
  { slug: 'programme-parrainage-voyageurs-fidelisation-lcd', categorySlug: 'visibilite', date: '2026-04-25', readTime: 4, title: 'Programme de parrainage voyageurs LCD : fidéliser et acquérir gratuitement' },
  { slug: 'revenue-management-hote-lcd-strategie', categorySlug: 'revenus', date: '2026-04-25', readTime: 8, title: 'Revenue management pour hôtes LCD : la stratégie des professionnels accessible à tous' },
  { slug: 'reseaux-sociaux-hote-lcd-strategie', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'Réseaux sociaux pour hôtes LCD : quelle stratégie adopter pour générer des réservations' },
  { slug: 'saisonnalite-lcd-revenus-annee-strategies', categorySlug: 'revenus', date: '2026-04-25', readTime: 7, title: 'Saisonnalité en LCD : comment lisser ses revenus sur toute l\'année' },
  { slug: 'seo-local-hote-lcd-etre-trouve-google', categorySlug: 'visibilite', date: '2026-04-25', readTime: 7, title: 'SEO local pour hôte LCD : comment être trouvé sur Google Maps et générer des réservations' },
  { slug: 'signaler-voyageur-airbnb-procedure', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Signaler un voyageur sur Airbnb : la procédure complète pour protéger son logement' },
  { slug: 'smoobu-avis-test-terrain-hotes-lcd', categorySlug: 'automatisation', date: '2026-04-25', readTime: 7, title: 'Smoobu : avis et test terrain pour hôtes LCD — ça vaut vraiment le coup ?' },
  { slug: 'sous-louer-airbnb-legalement-france', categorySlug: 'reglementation', date: '2026-04-25', readTime: 7, title: 'Sous-louer sur Airbnb légalement en France : ce que dit la loi en 2026' },
  { slug: 'strategie-prix-weekend-vs-semaine-lcd', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Prix week-end vs semaine en LCD : comment optimiser selon les jours' },
  { slug: 'superhote-avis-test-hotes-lcd', categorySlug: 'automatisation', date: '2026-04-25', readTime: 7, title: 'Superhôte Airbnb : avis et stratégies pour l\'obtenir et le conserver en 2026' },
  { slug: 'taxe-sejour-lcd-comment-la-collecter', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 6, title: 'Taxe de séjour en LCD : comment la collecter et la reverser correctement' },
  { slug: 'tva-location-meublee-courte-duree-guide', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 8, title: 'TVA en location meublée courte durée : qui est concerné et comment la gérer' },
  { slug: 'upselling-extras-hote-lcd-revenus', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Upselling et extras en LCD : comment proposer des services additionnels qui se vendent' },
  { slug: 'vrbo-homeaway-guide-hote-lcd', categorySlug: 'visibilite', date: '2026-04-25', readTime: 7, title: 'VRBO / Homeaway : guide complet pour hôtes LCD qui veulent diversifier leurs plateformes' },
  { slug: 'whatsapp-hotes-lcd-communication-voyageurs', categorySlug: 'automatisation', date: '2026-04-25', readTime: 5, title: 'WhatsApp pour hôtes LCD : comment l\'utiliser professionnellement avec ses voyageurs' },
  { slug: 'partenariats-locaux-hotes-lcd-restaurants-activites', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Partenariats locaux LCD : 7 types à mettre en place pour booster les avis' },
  { slug: 'email-marketing-newsletter-hote-lcd', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Email marketing pour hôte LCD : newsletter qui fait revenir tes voyageurs' },
  { slug: 'banque-objets-utiles-laisser-voyageur-lcd', categorySlug: 'ressources', date: '2026-04-25', readTime: 4, title: '15 objets utiles à laisser à tes voyageurs LCD : kit oubli, dépannage, plaisir' },
  { slug: 'modele-email-post-sejour-fideliser-voyageur', categorySlug: 'ressources', date: '2026-04-25', readTime: 4, title: 'Email post-séjour Airbnb : 4 modèles testés pour avoir 5★ et fidéliser' },
]
