export type BlogCategory =
  | 'revenus'
  | 'visibilite'
  | 'experience'
  | 'ressources'
  | 'automatisation'
  | 'reglementation'
  | 'conciergerie'
  | 'fiscalite'
  | 'driing'

export interface BlogArticle {
  slug: string
  categorySlug: BlogCategory
  date: string
  readTime: number
  title: string
}

export const BLOG_CATEGORIES: Record<BlogCategory, { label: string; color: string; bg: string }> = {
  revenus:        { label: 'Revenus',         color: '#B06010', bg: 'rgba(176,96,16,.1)'  },
  visibilite:     { label: 'Visibilité',      color: '#004C3F', bg: 'rgba(0,76,63,.1)'    },
  experience:     { label: 'Expérience',      color: '#92400E', bg: 'rgba(146,64,14,.1)'  },
  ressources:     { label: 'Ressources',      color: '#6D28D9', bg: 'rgba(109,40,217,.1)' },
  automatisation: { label: 'Automatisation',  color: '#2563EB', bg: 'rgba(37,99,235,.1)'  },
  reglementation: { label: 'Réglementation',  color: '#991B1B', bg: 'rgba(153,27,27,.1)'  },
  conciergerie:   { label: 'Conciergerie',    color: '#003329', bg: 'rgba(0,51,41,.1)'    },
  fiscalite:      { label: 'Fiscalité',       color: '#556B2F', bg: 'rgba(85,107,47,.1)'  },
  driing:         { label: 'Driing',          color: '#003329', bg: 'rgba(255,213,107,.18)' },
}

export const BLOG_ARTICLES: BlogArticle[] = [
  { slug: 'creer-conciergerie-airbnb-2025', categorySlug: 'conciergerie', date: '2026-05-02', readTime: 10, title: 'Créer sa conciergerie Airbnb en 2025 : les étapes essentielles pour démarrer' },
  { slug: 'driing-plateforme-vacances-sans-commissions', categorySlug: 'driing', date: '2026-05-02', readTime: 6, title: 'Driing : la plateforme de vacances sans commissions qui change la donne' },
  { slug: 'google-my-business-hotes-lcd', categorySlug: 'visibilite', date: '2026-05-02', readTime: 6, title: 'Pourquoi Google My Business est indispensable pour les hôtes LCD en 2025' },
  { slug: 'livret-accueil-digital-hotes-lcd', categorySlug: 'experience', date: '2026-05-02', readTime: 4, title: 'Livret d\'accueil digital : pourquoi c\'est devenu indispensable pour les hôtes LCD' },
  { slug: 'location-courte-duree-impots-france', categorySlug: 'fiscalite', date: '2026-05-02', readTime: 9, title: 'Location courte durée et impôts : ce que tout hôte doit savoir en France' },
  { slug: 'messages-airbnb-automatiser', categorySlug: 'automatisation', date: '2026-05-02', readTime: 4, title: 'Les 5 messages Airbnb à automatiser absolument dès cette semaine' },
  { slug: 'obtenir-avis-5-etoiles-airbnb', categorySlug: 'experience', date: '2026-05-02', readTime: 5, title: 'Comment obtenir plus d\'avis 5 étoiles sur Airbnb sans harceler tes voyageurs' },
  { slug: 'optimiser-annonce-airbnb', categorySlug: 'visibilite', date: '2026-05-02', readTime: 5, title: 'Optimiser son annonce Airbnb : les 8 éléments qui font vraiment la différence' },
  { slug: 'outils-gerer-location-courte-duree-2025', categorySlug: 'automatisation', date: '2026-05-02', readTime: 6, title: 'Les 7 outils indispensables pour gérer sa location courte durée en 2025' },
  { slug: 'reglementation-lcd-france-2026', categorySlug: 'reglementation', date: '2026-05-02', readTime: 8, title: 'Réglementation LCD France 2026 : tout ce qui change pour les hôtes' },
  { slug: 'reservation-directe-sans-commission', categorySlug: 'revenus', date: '2026-05-02', readTime: 8, title: 'Réservation directe sans commission : comment se lancer sans site web' },
  { slug: 'tarification-dynamique-lcd', categorySlug: 'revenus', date: '2026-05-02', readTime: 7, title: 'Tarification dynamique en location courte durée : par où commencer' },
  { slug: 'accueillir-famille-enfants-airbnb-equipement', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Accueillir une famille avec enfants en LCD : 15 équipements qui font la différence' },
  { slug: 'accueillir-voyageur-business-lcd-essentiels', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Accueillir un voyageur business : les 10 essentiels qui boostent ton ADR' },
  { slug: 'airdna-mode-emploi-hote-lcd-debutant', categorySlug: 'revenus', date: '2026-04-25', readTime: 5, title: 'AirDNA mode d\'emploi : utiliser les data marché pour optimiser ton tarif LCD' },
  { slug: 'assurance-lcd-5-garanties-indispensables-2026', categorySlug: 'reglementation', date: '2026-04-25', readTime: 6, title: 'Assurance LCD : les 5 garanties indispensables en 2026 (et celles inutiles)' },
  { slug: 'automatiser-caution-swikly-youka-test-terrain', categorySlug: 'automatisation', date: '2026-04-25', readTime: 5, title: 'Automatiser sa caution LCD : SwikLy vs Youka vs solution maison' },
  { slug: 'bail-mobilite-vs-courte-duree-differences', categorySlug: 'reglementation', date: '2026-04-25', readTime: 6, title: 'Bail mobilité vs location courte durée : les vraies différences pour un hôte' },
  { slug: 'banque-objets-utiles-laisser-voyageur-lcd', categorySlug: 'ressources', date: '2026-04-25', readTime: 4, title: '15 objets utiles à laisser à tes voyageurs LCD : kit oubli, dépannage, plaisir' },
  { slug: 'blog-hote-lcd-strategie-trafic-organique', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'Blog d\'hôte LCD : la stratégie pour générer du trafic organique en 2026' },
  { slug: 'bruit-reglement-interieur-lcd-efficace', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Bruit voyageur : le règlement intérieur LCD qui fait baisser les plaintes de 70 %' },
  { slug: 'budget-annuel-hote-lcd-grille-couts', categorySlug: 'revenus', date: '2026-04-25', readTime: 7, title: 'Budget annuel d\'un hôte LCD : la grille de coûts complète pour anticiper' },
  { slug: 'capteurs-iot-lcd-bruit-temperature-utile-ou-pas', categorySlug: 'automatisation', date: '2026-04-25', readTime: 6, title: 'Capteurs IoT pour LCD : bruit, température, ouverture — utile ou gadget ?' },
  { slug: 'chambres-hotes-vs-meuble-tourisme-differences', categorySlug: 'experience', date: '2026-04-25', readTime: 6, title: 'Chambres d\'hôtes vs meublé de tourisme : 7 différences que les hôtes ignorent' },
  { slug: 'check-in-tardif-4-solutions-sans-cles', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Check-in tardif Airbnb : 4 solutions sans clé ni présence physique' },
  { slug: 'checklist-preparation-logement-avant-1ere-reservation', categorySlug: 'ressources', date: '2026-04-25', readTime: 7, title: 'Checklist préparation logement LCD : 47 points avant ta 1ère réservation' },
  { slug: 'communiquer-voyageurs-etrangers-5-regles-multilingue', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Communiquer avec des voyageurs étrangers en LCD : 5 règles qui changent les avis' },
  { slug: 'contrat-mandat-conciergerie-lcd-modele-clauses', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 6, title: 'Contrat de mandat conciergerie LCD : les 8 clauses indispensables en 2026' },
  { slug: 'description-airbnb-500-caracteres-convertit-2026', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'Description Airbnb : les 500 premiers caractères qui décident de la réservation' },
  { slug: 'diversifier-revenus-lcd-au-dela-nuitees', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Diversifier ses revenus LCD : 7 sources au-delà du tarif nuitée' },
  { slug: 'droits-voisins-lcd-copropriete-litiges', categorySlug: 'reglementation', date: '2026-04-25', readTime: 5, title: 'Droits des voisins en LCD : éviter et gérer les litiges en copropriété' },
  { slug: 'email-marketing-newsletter-hote-lcd', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Email marketing pour hôte LCD : newsletter qui fait revenir tes voyageurs' },
  { slug: 'equipe-menage-conciergerie-recruter-fideliser', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 6, title: 'Équipe ménage conciergerie : recruter, former, fidéliser en 2026' },
  { slug: 'erp-classement-meuble-tourisme-lcd', categorySlug: 'reglementation', date: '2026-04-25', readTime: 5, title: 'ERP et meublé de tourisme classé : faut-il faire les démarches en 2026 ?' },
  { slug: 'formulaire-fiche-police-lcd-obligatoire', categorySlug: 'ressources', date: '2026-04-25', readTime: 4, title: 'Fiche de police LCD : remplir et conserver le formulaire obligatoire' },
  { slug: 'frais-menage-airbnb-combien-facturer-2026', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Frais de ménage Airbnb : combien facturer en 2026 sans pénaliser ses réservations' },
  { slug: 'gmb-questions-reponses-hotes-lcd-optimiser', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Google My Business : la section Questions/Réponses sous-utilisée par 90% des hôtes LCD' },
  { slug: 'guide-fiscal-debutant-hote-airbnb-2026', categorySlug: 'ressources', date: '2026-04-25', readTime: 6, title: 'Guide fiscal débutant 2026 : déclarer ses revenus Airbnb sans erreur' },
  { slug: 'instagram-reels-tiktok-lcd-attirer-voyageurs', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Instagram Reels & TikTok pour LCD : 6 formats vidéo qui convertissent' },
  { slug: 'integration-calendrier-perso-airbnb-google', categorySlug: 'automatisation', date: '2026-04-25', readTime: 4, title: 'Intégrer ton calendrier Airbnb dans Google Calendar perso : 5 minutes' },
  { slug: 'inventaire-logement-airbnb-modele-photos', categorySlug: 'ressources', date: '2026-04-25', readTime: 5, title: 'Inventaire logement Airbnb : le modèle photo qui te protège des litiges' },
  { slug: 'last-minute-vs-early-booking-strategie-2026', categorySlug: 'revenus', date: '2026-04-25', readTime: 5, title: 'Last-minute vs early booking : la stratégie de remises temporelles en 2026' },
  { slug: 'lmnp-vs-lmp-changement-2026-impact', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 7, title: 'LMNP ou LMP en 2026 : ce qui change pour les hôtes Airbnb français' },
  { slug: 'logiciels-conciergerie-comparatif-2026', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 6, title: 'Logiciels conciergerie LCD : comparatif des 5 PMS leaders en 2026' },
  { slug: 'make-zapier-workflow-airbnb-no-code-debutant', categorySlug: 'automatisation', date: '2026-04-25', readTime: 6, title: 'Make ou Zapier pour Airbnb : automatiser ses flows en no-code' },
  { slug: 'marge-nette-par-nuitee-suivi-precis', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Marge nette par nuitée : le seul KPI qui compte vraiment en LCD' },
  { slug: 'messagerie-unifiee-3-plateformes-tester', categorySlug: 'automatisation', date: '2026-04-25', readTime: 5, title: 'Messagerie unifiée Airbnb + Booking + direct : 3 outils à tester en 2026' },
  { slug: 'micro-bic-abattement-2026-airbnb', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 10, title: 'Abattement micro-BIC 2026 : ce que la loi Le Meur coûte vraiment aux hôtes Airbnb' },
  { slug: 'modele-email-post-sejour-fideliser-voyageur', categorySlug: 'ressources', date: '2026-04-25', readTime: 4, title: 'Email post-séjour Airbnb : 4 modèles testés pour avoir 5★ et fidéliser' },
  { slug: 'mots-cles-titre-annonce-airbnb-eviter-spam-detection', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Titre Airbnb 2026 : 9 mots-clés à éviter qui déclenchent le filtre anti-spam' },
  { slug: 'numero-enregistrement-lcd-obtenir-etapes-pratiques', categorySlug: 'reglementation', date: '2026-04-25', readTime: 5, title: 'Numéro d\'enregistrement LCD : 8 étapes pratiques pour l\'obtenir avant mai 2026' },
  { slug: 'optimiser-annonce-booking-com-2026-classement', categorySlug: 'visibilite', date: '2026-04-25', readTime: 7, title: 'Optimiser son annonce Booking.com en 2026 : 9 leviers de classement' },
  { slug: 'outils-gratuits-indispensables-demarrer-lcd-2026', categorySlug: 'ressources', date: '2026-04-25', readTime: 6, title: 'Outils gratuits indispensables pour démarrer en LCD en 2026 : la liste complète' },
  { slug: 'partenariats-locaux-hotes-lcd-restaurants-activites', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Partenariats locaux LCD : 7 types à mettre en place pour booster les avis' },
  { slug: 'photo-couverture-airbnb-7-criteres-algo-computer-vision', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'Photo de couverture Airbnb : les 7 critères de l\'algo Computer Vision en 2026' },
  { slug: 'photos-avant-apres-home-staging-lcd', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Photos avant-après home staging LCD : 5 transformations à 200 €' },
  { slug: 'point-mort-lcd-calcul-rentabilite-hote', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Calculer son point mort en location courte durée : la méthode en 4 lignes' },
  { slug: 'prix-min-max-airbnb-fourchette-tarifaire', categorySlug: 'revenus', date: '2026-04-25', readTime: 5, title: 'Prix min / prix max Airbnb : la fourchette tarifaire qui maximise ton revenu' },
  { slug: 'profil-hote-airbnb-bio-photo-confiance', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Profil hôte Airbnb : photo et bio qui inspirent confiance et augmentent les réservations' },
  { slug: 'programme-parrainage-voyageurs-fidelisation-lcd', categorySlug: 'visibilite', date: '2026-04-25', readTime: 4, title: 'Programme de parrainage voyageurs LCD : fidéliser et acquérir gratuitement' },
  { slug: 'prospection-conciergerie-trouver-premier-mandat', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 6, title: 'Conciergerie LCD : 7 stratégies pour décrocher ton premier mandat' },
  { slug: 'recherches-voyageurs-airbnb-tendances-emergentes-2026', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Recherches voyageurs Airbnb 2026 : 5 tendances émergentes à capter' },
  { slug: 'recuperer-mauvais-avis-airbnb-methode-5-etapes', categorySlug: 'experience', date: '2026-04-25', readTime: 6, title: 'Récupérer un mauvais avis Airbnb : la méthode en 5 étapes pour limiter les dégâts' },
  { slug: 'refacturer-degat-voyageur-airbnb-procedure', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Refacturer un dégât voyageur : procédure Airbnb, Booking et direct (2026)' },
  { slug: 'regime-reel-vs-micro-bic-decision-2026', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 6, title: 'Micro-BIC ou régime réel en LCD : la décision avec calculs en 2026' },
  { slug: 'rgpd-donnees-voyageurs-airbnb-conformite', categorySlug: 'reglementation', date: '2026-04-25', readTime: 5, title: 'RGPD et données voyageurs : conformité hôte LCD en 2026' },
  { slug: 'saisonnalite-tarif-region-france-lcd-2026', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Saisonnalité LCD par région française : la grille tarifaire 2026' },
  { slug: 'scaler-conciergerie-5-30-mandats-process', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 6, title: 'Scaler une conciergerie de 5 à 30 mandats : les process à mettre en place' },
  { slug: 'scripts-check-out-automatique-lcd', categorySlug: 'automatisation', date: '2026-04-25', readTime: 5, title: 'Scripts de check-out automatiques : 6 messages à programmer pour zéro friction' },
  { slug: 'seo-local-hote-lcd-google-maps-visibilite', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'SEO local pour hôte LCD : ressortir sur Google Maps en 2026' },
  { slug: 'serrure-connectee-igloohome-nuki-comparatif-2026', categorySlug: 'automatisation', date: '2026-04-25', readTime: 6, title: 'Serrure connectée LCD : Igloohome vs Nuki vs Master Lock — comparatif 2026' },
  { slug: 'signaletique-interieure-lcd-reduit-questions', categorySlug: 'experience', date: '2026-04-25', readTime: 4, title: 'Signalétique intérieure LCD : réduire les questions voyageurs de 50 %' },
  { slug: 'sortir-mauvais-client-conciergerie-procedure', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 5, title: 'Sortir un mauvais client de conciergerie : la procédure en 5 étapes' },
  { slug: 'statistiques-annonce-airbnb-4-kpis-essentiels', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'Statistiques Airbnb : les 4 KPIs essentiels que les hôtes ignorent' },
  { slug: 'stripe-paiement-direct-lcd-mise-en-place', categorySlug: 'automatisation', date: '2026-04-25', readTime: 5, title: 'Stripe pour la réservation directe LCD : mise en place et paramétrage 2026' },
  { slug: 'tarif-conciergerie-lcd-grille-marche-2026', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 5, title: 'Tarif conciergerie LCD 2026 : la grille du marché par zone et prestation' },
  { slug: 'tarif-hebdomadaire-vs-nuitee-quand-preferer', categorySlug: 'revenus', date: '2026-04-25', readTime: 5, title: 'Tarif hebdomadaire vs nuitée : quand préférer chaque modèle (avec calculs)' },
  { slug: 'taxe-sejour-lcd-comment-collecter', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 5, title: 'Taxe de séjour en LCD : comment la collecter sans erreur en 2026' },
  { slug: 'top-7-erreurs-nouveaux-hotes-lcd-eviter', categorySlug: 'ressources', date: '2026-04-25', readTime: 6, title: 'Top 7 des erreurs des nouveaux hôtes LCD (et comment les éviter)' },
  { slug: 'travaux-energetiques-lcd-aides-maprimerenov-2026', categorySlug: 'reglementation', date: '2026-04-25', readTime: 7, title: 'Travaux énergétiques en LCD : MaPrimeRénov 2026 et autres aides pour ton DPE' },
  { slug: 'trousse-premier-secours-lcd-equipement-obligatoire', categorySlug: 'ressources', date: '2026-04-25', readTime: 4, title: 'Trousse de premier secours LCD : la liste obligatoire et les bonus à ajouter' },
  { slug: 'tva-petit-dejeuner-lcd-seuil-37500-2026-detail', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 6, title: 'TVA et petit-déjeuner en LCD : pourquoi le seuil 37 500 € t\'arrive plus vite que prévu' },
  { slug: 'welcome-bag-lcd-12-idees-marquantes-budget', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Welcome bag LCD : 12 idées qui marquent les voyageurs (avec budget)' },
  { slug: 'algorithme-airbnb-2026-criteres-classement', categorySlug: 'visibilite', date: '2026-04-24', readTime: 8, title: 'Algorithme Airbnb 2026 : les 4 critères qui décident vraiment de ton classement' },
  { slug: 'chatgpt-booking-com-impact-hotes-lcd', categorySlug: 'visibilite', date: '2026-04-24', readTime: 7, title: 'Booking.com x ChatGPT : ce que l\'intégration IA change concrètement pour ton annonce' },
  { slug: 'cybevasion-rachetee-holidu-impact-hotes-alternatives', categorySlug: 'revenus', date: '2026-04-24', readTime: 6, title: 'Cybevasion rachetée par Holidu : ce que ça change pour les hôtes et les meilleures alternatives' },
  { slug: 'dpe-location-courte-duree-obligations-2025-2034', categorySlug: 'reglementation', date: '2026-04-24', readTime: 7, title: 'DPE en location courte durée : ce qui est déjà interdit et l\'horizon 2034 que tu ne peux pas ignorer' },
  { slug: 'hospitable-tarification-dynamique-incluse-pms-fin-outils-seuls', categorySlug: 'automatisation', date: '2026-04-24', readTime: 7, title: 'Hospitable intègre la tarification dynamique : la fin des outils de pricing séparés pour les petits hôtes ?' },
  { slug: 'numero-enregistrement-lcd-20-mai-2026-demarches', categorySlug: 'reglementation', date: '2026-04-24', readTime: 6, title: 'Numéro d\'enregistrement LCD obligatoire dès le 20 mai 2026 : les démarches à faire maintenant' },
  { slug: 'photos-airbnb-computer-vision-ia-optimiser', categorySlug: 'visibilite', date: '2026-04-24', readTime: 7, title: 'Photos Airbnb et Computer Vision : comment l\'IA juge tes images et ce qu\'il faut changer' },
  { slug: 'sejours-longs-lcd-strategie-revenus-basse-saison', categorySlug: 'revenus', date: '2026-04-24', readTime: 7, title: 'Séjours longs en LCD : la stratégie complète pour booster ton taux d\'occupation de 15 % en basse saison' },
  { slug: 'tva-location-courte-duree-2026', categorySlug: 'fiscalite', date: '2026-04-24', readTime: 8, title: 'TVA en location courte durée : qui est concerné en 2026 et comment se préparer' },
  { slug: 'workation-lcd-logement-equiper-louer-cher-hors-saison', categorySlug: 'revenus', date: '2026-04-24', readTime: 7, title: 'Workation en LCD : les 5 équipements qui te permettent de louer 30 % plus cher hors saison' },
  { slug: 'airbnb-vs-booking-com-location-courte-duree', categorySlug: 'visibilite', date: '2026-03-25', readTime: 8, title: 'Airbnb vs Booking.com : lequel choisir pour ton logement LCD ?' },
  { slug: 'amenager-logement-location-courte-duree-petit-budget', categorySlug: 'experience', date: '2026-03-25', readTime: 8, title: 'Aménager son logement pour la LCD avec un petit budget' },
  { slug: 'appel-decouverte-jason-marinho-accompagnement-lcd', categorySlug: 'ressources', date: '2026-03-25', readTime: 5, title: 'L\'appel découverte Jason Marinho : à qui ça s\'adresse et ce qu\'on y fait en 30 minutes' },
  { slug: 'assurance-location-courte-duree-airbnb-couverture', categorySlug: 'reglementation', date: '2026-03-25', readTime: 8, title: 'Assurance en location courte durée : ce que couvre vraiment Airbnb (et ce qu\'il ne couvre pas)' },
  { slug: 'attirer-teletravailleur-nomade-digital-location-courte-duree', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Télétravail et LCD : comment attirer les nomades digitaux dans ton logement' },
  { slug: 'base-voyageurs-fideles-location-directe-durable', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Construire une base de voyageurs fidèles : la clé de la location directe durable' },
  { slug: 'basse-saison-location-courte-duree-strategies-reservations', categorySlug: 'revenus', date: '2026-03-25', readTime: 8, title: 'Basse saison en LCD : 7 stratégies concrètes pour remplir ton calendrier' },
  { slug: 'booking-com-hotes-location-courte-duree-guide', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Booking.com pour les hôtes LCD : tout ce qu\'il faut savoir avant de s\'inscrire' },
  { slug: 'chambres-hotes-plateforme-jason-marinho-ressources', categorySlug: 'ressources', date: '2026-03-25', readTime: 6, title: 'Chambres d\'hôtes : comment la plateforme Jason Marinho t\'aide à développer ton activité' },
  { slug: 'check-in-location-courte-duree-boite-a-cles-serrure-connectee', categorySlug: 'automatisation', date: '2026-03-25', readTime: 7, title: 'Check-in en LCD : accueil en personne, boîte à clés ou serrure connectée ?' },
  { slug: 'checklist-menage-professionnelle-location-courte-duree', categorySlug: 'experience', date: '2026-03-25', readTime: 6, title: 'Checklist ménage professionnelle pour hôte LCD (+ gabarit à télécharger)' },
  { slug: 'communaute-lcd-groupes-hotes-entraide-facebook', categorySlug: 'ressources', date: '2026-03-25', readTime: 6, title: 'Communauté LCD : pourquoi les meilleurs hôtes ne travaillent pas seuls' },
  { slug: 'conciergerie-airbnb-faire-appel-choisir', categorySlug: 'conciergerie', date: '2026-03-25', readTime: 7, title: 'Conciergerie Airbnb : faut-il en faire appel à une et comment bien la choisir ?' },
  { slug: 'conciergeries-lcd-ressources-plateforme-jason-marinho', categorySlug: 'conciergerie', date: '2026-03-25', readTime: 6, title: 'Conciergeries LCD : les ressources de la plateforme qui font gagner du temps à grande échelle' },
  { slug: 'declarer-activite-location-courte-duree-france-demarches', categorySlug: 'reglementation', date: '2026-03-25', readTime: 9, title: 'Déclarer son activité LCD en France : les démarches administratives à connaître' },
  { slug: 'description-logement-convertit-reservation-directe', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Rédiger une description de logement qui convertit en réservation directe' },
  { slug: 'erreurs-debutant-location-courte-duree-premier-logement', categorySlug: 'revenus', date: '2026-03-25', readTime: 9, title: 'Premier logement LCD : les 10 erreurs à éviter quand on se lance' },
  { slug: 'fixer-prix-minimum-airbnb-lcd', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Comment fixer son prix minimum sur Airbnb sans se brader' },
  { slug: 'fixer-prix-reservation-directe-location-courte-duree', categorySlug: 'revenus', date: '2026-03-25', readTime: 6, title: 'Comment fixer son prix pour la réservation directe : ni trop cher, ni bradé' },
  { slug: 'formation-google-my-business-lcd-contenu', categorySlug: 'visibilite', date: '2026-03-25', readTime: 5, title: 'Formation Google My Business pour la LCD : ce qu\'elle contient et pourquoi la suivre' },
  { slug: 'formations-lcd-disponibles-plateforme-jason-marinho', categorySlug: 'ressources', date: '2026-03-25', readTime: 5, title: 'Formations LCD disponibles sur la plateforme : ce que tu peux suivre maintenant et ce qui arrive' },
  { slug: 'gabarits-messages-lcd-hotes-templates', categorySlug: 'automatisation', date: '2026-03-25', readTime: 5, title: 'Gabarits de messages LCD : arrête de réécrire les mêmes messages à chaque voyageur' },
  { slug: 'gerer-mauvais-avis-airbnb-reponse-hote', categorySlug: 'experience', date: '2026-03-25', readTime: 6, title: 'Comment gérer un mauvais avis sur Airbnb sans perdre ton classement' },
  { slug: 'gerer-voyageurs-difficiles-location-courte-duree', categorySlug: 'experience', date: '2026-03-25', readTime: 7, title: 'Voyageurs difficiles en LCD : comment prévenir et gérer les situations problématiques' },
  { slug: 'google-my-business-reservations-directes-hotes-lcd', categorySlug: 'visibilite', date: '2026-03-25', readTime: 8, title: 'Google My Business pour hôtes LCD : le levier gratuit qui génère des réservations directes' },
  { slug: 'instagram-hotes-lcd-attirer-voyageurs-reservations-directes', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Instagram pour hôtes LCD : comment attirer des voyageurs directement depuis les réseaux' },
  { slug: 'livret-accueil-digital-creer-location-courte-duree', categorySlug: 'experience', date: '2026-03-25', readTime: 7, title: 'Livret d\'accueil digital : pourquoi c\'est devenu indispensable et comment en créer un' },
  { slug: 'location-directe-pourquoi-saffranchir-plateformes', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Location en direct : pourquoi de plus en plus d\'hôtes s\'affranchissent des plateformes' },
  { slug: 'mesurer-performance-canal-reservation-directe-kpi', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Mesurer la performance de ton canal de réservation directe : les chiffres qui comptent vraiment' },
  { slug: 'partenaires-lcd-outils-valides-terrain-hotes', categorySlug: 'ressources', date: '2026-03-25', readTime: 6, title: 'Partenaires LCD : pourquoi les outils que tu utilises méritent d\'être validés avant d\'y mettre ton argent' },
  { slug: 'photographier-logement-location-courte-duree-smartphone', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Comment photographier son logement LCD soi-même (sans matériel pro)' },
  { slug: 'pms-logiciel-gestion-location-courte-duree-debutant', categorySlug: 'automatisation', date: '2026-03-25', readTime: 8, title: 'PMS pour débutant : quel logiciel choisir selon ton profil LCD ?' },
  { slug: 'politique-annulation-location-directe-hote', categorySlug: 'revenus', date: '2026-03-25', readTime: 6, title: 'Gérer les annulations en location directe : quelle politique adopter et comment l\'appliquer' },
  { slug: 'pourquoi-creer-compte-plateforme-jason-marinho', categorySlug: 'ressources', date: '2026-03-25', readTime: 5, title: 'Pourquoi créer un compte gratuit sur la plateforme Jason Marinho dès maintenant' },
  { slug: 'premieres-reservations-directes-sans-audience-site-web', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Comment obtenir ses premières réservations directes sans audience ni site web' },
  { slug: 'securiser-paiement-reservation-directe-sans-airbnb', categorySlug: 'revenus', date: '2026-03-25', readTime: 7, title: 'Réservation directe : comment sécuriser le paiement et protéger ton logement sans Airbnb' },
  { slug: 'site-reservation-directe-location-courte-duree', categorySlug: 'revenus', date: '2026-03-25', readTime: 8, title: 'Créer son premier site de réservation directe en LCD : par où commencer' },
  { slug: 'tarification-dynamique-pricelabs-wheelhouse-beyond-comparatif', categorySlug: 'revenus', date: '2026-03-25', readTime: 8, title: 'Tarification dynamique en LCD : Pricelabs, Wheelhouse ou Beyond — lequel choisir ?' },
  { slug: 'titre-annonce-airbnb-optimiser-clics-visibilite', categorySlug: 'visibilite', date: '2026-03-25', readTime: 6, title: 'Titre d\'annonce Airbnb : comment écrire un titre qui fait cliquer' },
  { slug: 'verification-voyageurs-avant-accepter-reservation-lcd', categorySlug: 'experience', date: '2026-03-25', readTime: 6, title: 'Comment vérifier un voyageur avant d\'accepter sa réservation en LCD' },
]
