export type ChangelogTag = 'nouveau' | 'amélioration' | 'correction' | 'important'

export interface ChangelogEntry {
  id: string
  date: string // ISO 8601
  tag: ChangelogTag
  title: string
  description: string
}

export const CHANGELOG: ChangelogEntry[] = [
  // ─── Mai 2026 ──────────────────────────────────────────────────
  {
    id: 'formations-page-refonte-mai-2026',
    date: '2026-05-01',
    tag: 'amélioration',
    title: 'Page Formations repensée : parcours mis en avant + favoris en 1 clic',
    description: '"Parcours d\'apprentissage" sort enfin de l\'ombre, hero card en haut de page pour te guider étape par étape. Tu peux maintenant mettre une formation en favori d\'un clic sur le cœur ❤️ directement sur sa carte. La page Mes favoris affiche les formations et leçons bookmarkées dans 2 sections distinctes.',
  },
  {
    id: 'rail-formation-agrandie-mai-2026',
    date: '2026-05-01',
    tag: 'amélioration',
    title: 'Rail latérale des formations agrandie',
    description: 'La rail droite des leçons (Progression, Navigation, Notes, Sur cette page) gagne 23 % de largeur pour respirer enfin. Les liens "Sur cette page" scrollent maintenant correctement vers le titre cliqué.',
  },
  {
    id: 'photographie-lcd-mai-2026',
    date: '2026-04-30',
    tag: 'nouveau',
    title: 'Nouvelle formation : Faire des photos qui font cliquer',
    description: 'La 17e formation est en ligne. Apprends à transformer ton annonce avec ton seul smartphone : composition, lumière naturelle, mise en scène, retouche Snapseed, ordre des photos. 6 modules, 19 leçons. Une bonne photo de couverture peut multiplier tes réservations par 1,5.',
  },
  {
    id: 'gerer-incidents-mai-2026',
    date: '2026-04-30',
    tag: 'nouveau',
    title: 'Nouvelle formation : Gérer les incidents et litiges en LCD',
    description: 'La 18e formation t\'apprend à anticiper, gérer et facturer chaque incident sans paniquer : caution Stripe, AirCover Airbnb, Booking, état des lieux, médiation. Plaintes voisins, dégâts, voyageurs problématiques, no-show : tout y est. 6 modules, 22 leçons.',
  },
  {
    id: 'performances-dashboard-mai-2026',
    date: '2026-04-29',
    tag: 'nouveau',
    title: 'Performances : ton tableau de bord de pilotage',
    description: 'Une nouvelle section dans le dashboard pour piloter ton activité : taux d\'occupation par logement, revenus mensuels sur 12 mois, prix moyen par nuit, comparateur de tes logements, sources de réservation, insights automatiques. Tout ce qu\'il te faut pour savoir quand baisser tes prix ou monter en gamme.',
  },
  {
    id: 'fiche-incident-sejour-mai-2026',
    date: '2026-04-28',
    tag: 'nouveau',
    title: 'Fiche incident par séjour',
    description: 'Tu peux maintenant signaler chaque incident lié à un séjour directement depuis la fiche voyageur : linge taché, casse, dégradation, vol, retard de restitution, plainte voisin… Avec photo, montant de caution à appliquer et statut (ouvert / résolu / remboursé). Tes preuves sont organisées en 1 endroit.',
  },
  {
    id: 'auto-checklist-contrats-mai-2026',
    date: '2026-04-27',
    tag: 'amélioration',
    title: 'Checklist contrat auto-cochée à chaque étape',
    description: 'Ton suivi opérationnel se met à jour tout seul : "Contrat envoyé" coché à la création, "Contrat signé" à la signature, "Solde reçu" et "Caution reçue" cochés automatiquement quand le voyageur paye sur Stripe. Plus besoin de cocher à la main, et la checklist est synchronisée entre calendrier et fiche voyageur.',
  },
  {
    id: 'calendrier-barre-sejour-mai-2026',
    date: '2026-04-27',
    tag: 'amélioration',
    title: 'Calendrier : barre continue entre arrivée et départ',
    description: 'Avant, l\'arrivée et le départ s\'affichaient comme 2 blocs séparés sur le calendrier. Maintenant, une bande verte continue traverse toute la durée du séjour, beaucoup plus lisible d\'un coup d\'œil. Bonus : un bouton "Gabarit" sur chaque alerte pour ouvrir le bon message-type prêt à l\'emploi.',
  },
  {
    id: 'ical-sync-logements-mai-2026',
    date: '2026-04-26',
    tag: 'nouveau',
    title: 'Synchronisation iCal multi-plateformes',
    description: 'Ajoute tes liens iCal Airbnb, Booking, Vrbo et autres plateformes directement sur la fiche logement. Les réservations externes apparaissent automatiquement dans ton calendrier intégré. Plus de double-réservation par oubli de bloquer une date.',
  },
  {
    id: 'profil-chez-nous-enrichi-mai-2026',
    date: '2026-04-25',
    tag: 'amélioration',
    title: 'Profil membre Chez Nous enrichi',
    description: 'Le profil public d\'un membre dans la communauté Chez Nous affiche maintenant les plateformes utilisées (Airbnb, Booking…), les catégories où il s\'exprime le plus, sa dernière activité, ses badges (mode clair lisible enfin) et tu accèdes à ton propre profil en 1 clic depuis le menu en haut à droite.',
  },
  {
    id: 'profil-mes-coordonnees-mai-2026',
    date: '2026-04-24',
    tag: 'amélioration',
    title: 'Page profil refondue avec barre de progression',
    description: 'Refonte complète de la page profil en cartes thématiques (Identité, Coordonnées, Encaissements, Profil Chez Nous), progression visible en pourcentage, layout en 2-3 colonnes sur ordinateur. Trouve et complète ton profil 3x plus vite.',
  },
  {
    id: 'chez-nous-mobile-bubble-mai-2026',
    date: '2026-04-23',
    tag: 'amélioration',
    title: 'Chez Nous : catégories en bulles sur mobile',
    description: 'Les catégories de Chez Nous s\'affichent maintenant en bulles rondes "stories" sur mobile (style Instagram), beaucoup plus tactiles. Un bouton "Inviter des amis hôtes" en pleine largeur fait son apparition pour partager la communauté en 1 geste.',
  },
  {
    id: 'fixes-mobile-light-mode-mai-2026',
    date: '2026-04-22',
    tag: 'correction',
    title: 'Corrections mobile et mode clair',
    description: 'Sidebar du dashboard qui défilait mal sur iPhone Safari → corrigée. Calendrier surchargé sur mobile → header épuré avec 3 KPIs essentiels. Bouton "Inviter" jaune sur fond blanc invisible → contraste corrigé. Site public bloqué par DDoS Vercel après refresh intensifs → diagnostiqué.',
  },

  // ─── Avril 2026 (pre-existant) ─────────────────────────────────
  {
    id: 'formation-booking-com-apr-2026',
    date: '2026-04-25',
    tag: 'nouveau',
    title: 'Nouvelle formation : Maîtriser Booking.com',
    description: 'La 16e formation est en ligne, entièrement dédiée à Booking.com : algorithme 2026, programme Genius, intégration ChatGPT pour tes annonces, et stratégie de prix. 7 modules, 14 leçons complètes. Accessible depuis le catalogue formations.',
  },
  {
    id: 'blog-132-articles-apr-2026',
    date: '2026-04-25',
    tag: 'nouveau',
    title: 'Blog LCD, 70 nouveaux articles publiés',
    description: 'Le blog passe à 132 articles sur la location courte durée. Nouveaux sujets : fiscalité 2026, réglementation (Loi Le Meur), tarification dynamique, automatisation, conciergerie, expérience voyageurs, Airbnb vs Booking, DPE, algorithme Airbnb 2026… Retrouve tout sur jasonmarinho.com/blog.',
  },
  {
    id: 'hub-services-apr-2026',
    date: '2026-04-25',
    tag: 'nouveau',
    title: 'Hub Services, tous les outils en un endroit',
    description: 'Une nouvelle page /services centralise l\'ensemble des ressources disponibles : outils gratuits (calculateur, simulateur fiscal, contrat type…), formations, guides et ressources. Plus besoin de chercher, tout est là.',
  },
  {
    id: 'pour-qui-profils-apr-2026',
    date: '2026-04-25',
    tag: 'amélioration',
    title: 'Pages "Pour qui", ressources par profil',
    description: 'Les pages profil (gîtes, chambres d\'hôtes, conciergeries, membres Driing) ont été enrichies avec des formations recommandées spécifiques à chaque activité, des ressources ciblées et une FAQ adaptée. Retrouve ce qui te concerne directement sur jasonmarinho.com/pour-qui.',
  },
  {
    id: 'dashboard-perf-lightmode-apr-2026',
    date: '2026-04-25',
    tag: 'amélioration',
    title: 'Dashboard, chargement plus rapide, mode clair corrigé',
    description: 'Plusieurs optimisations ont été appliquées : chargement initial réduit de 30-40 %, police optimisée (Fraunces + Outfit via next/font), et mode clair entièrement corrigé, plus aucun fond blanc illisible. Le dashboard est maintenant fluide sur mobile comme sur desktop.',
  },
  {
    id: 'soutenir-idees-vote-apr-2026',
    date: '2026-04-20',
    tag: 'nouveau',
    title: 'Vote & idées, propose des fonctionnalités',
    description: 'Une nouvelle section "Vote & propose des idées" est disponible sur la page Contributeur. Tu peux soumettre tes idées en une phrase et voter pour celles des autres membres. Les idées les plus votées passent en priorité dans la roadmap. Les statuts (proposée, planifiée, réalisée) sont mis à jour au fil du temps.',
  },
  {
    id: 'soutenir-refonte-v2-apr-2026',
    date: '2026-04-20',
    tag: 'amélioration',
    title: 'Page Contributeur, refonte complète',
    description: 'La page Contributeur a été entièrement repensée : bouton retour, montant libre sans suggestions imposées, avantages affichés en cartes visuelles colorées (badge permanent, accès direct, idées en priorité, accès anticipé), et nouvelle section vote d\'idées. Plus de barrière à la contribution, tu mets ce que tu veux.',
  },
  {
    id: 'calendrier-mobile-apr-2026',
    date: '2026-04-20',
    tag: 'amélioration',
    title: 'Calendrier, affichage mobile amélioré',
    description: 'Le panneau d\'alertes du calendrier est maintenant scrollable horizontalement sur mobile. Les colonnes ont une largeur minimale pour rester lisibles, et la légende se masque pour libérer de l\'espace. Plus pratique pour gérer tes séjours depuis ton téléphone.',
  },
  {
    id: 'accueil-greeting-apr-2026',
    date: '2026-04-20',
    tag: 'amélioration',
    title: 'Accueil, Bonjour / Bonsoir selon l\'heure',
    description: 'La page d\'accueil te salue maintenant avec "Bonjour" ou "Bonsoir" selon l\'heure de Paris. Un détail, mais ça compte.',
  },
  {
    id: 'plan-gating-apr-2026',
    date: '2026-04-19',
    tag: 'important',
    title: 'Accès par plan, Découverte, Standard, Driing',
    description: 'La plateforme adapte maintenant ce que tu vois selon ton plan. En Découverte : 2 formations au choix, actualités récentes, accès à la communauté et aux gabarits. En Standard : 14 formations complètes, journal des revenus, contrats illimités + Stripe, codes promo partenaires. Tout est automatique, rien à configurer.',
  },
  {
    id: 'abonnement-stripe-apr-2026',
    date: '2026-04-19',
    tag: 'important',
    title: 'Abonnements Standard & Membre Driing, paiement Stripe',
    description: 'Tu peux maintenant souscrire au plan Standard directement depuis ton espace (1,98 €/mois Membre Fondateur, prix bloqué à vie). Le plan Membre Driing est disponible à 0,98 €/mois pour les clients Driing actifs. Paiement sécurisé via Stripe, résiliation à tout moment depuis le portail.',
  },
  {
    id: 'tarifs-membre-fondateur-apr-2026',
    date: '2026-04-19',
    tag: 'important',
    title: 'Tarif Membre Fondateur, 1,98 €/mois à vie',
    description: 'Les premiers membres bénéficient d\'un prix bloqué à 1,98 €/mois (ou 19,98 €/an) tant que leur abonnement reste actif. Le tarif public passera à 3,98 €/mois à la fin de la phase lancement. C\'est le bon moment.',
  },
  {
    id: 'formations-2-choix-apr-2026',
    date: '2026-04-19',
    tag: 'amélioration',
    title: 'Formations, 2 formations au choix en Découverte',
    description: 'Les membres en Découverte peuvent maintenant choisir librement 2 formations parmi les 14 disponibles. Commence par celles qui t\'intéressent le plus, elles restent accessibles à vie. Passe en Standard pour tout débloquer.',
  },
  {
    id: 'soutenir-page-apr-2026',
    date: '2026-04-19',
    tag: 'nouveau',
    title: 'Page "Soutenir", contribuer librement à la plateforme',
    description: 'Une page dédiée permet de soutenir librement le développement de la plateforme, sans obligation. Contribution libre à partir de 2,98 €, paiement sécurisé via Stripe. Accessible depuis la page tarifs et le menu.',
  },
  {
    id: 'abonnement-dashboard-refonte-apr-2026',
    date: '2026-04-19',
    tag: 'amélioration',
    title: 'Dashboard Abonnement, refonte complète',
    description: 'La page Abonnement a été entièrement repensée : plan actuel bien visible, liste des fonctionnalités par plan, CTA vers Stripe pour upgrader ou gérer son abonnement, section Driing avec formulaire de demande. Plus clair, plus complet.',
  },
  {
    id: 'actualites-lcd-page-apr-2026',
    date: '2026-04-19',
    tag: 'nouveau',
    title: 'Actualités LCD, nouvelle section',
    description: 'Une nouvelle section "Actualités" est disponible dans ton espace. Elle rassemble les infos importantes du moment : nouvelles obligations, changements fiscaux, évolutions des plateformes… Le tout trié et résumé pour toi, avec un lien direct vers la source.',
  },
  {
    id: 'revenus-guide-fiscalite-apr-2026',
    date: '2026-04-19',
    tag: 'nouveau',
    title: 'Revenus, guide fiscalité 2026 intégré',
    description: 'Un guide clair sur les régimes fiscaux est maintenant accessible directement depuis la page Revenus. Tu y retrouves les seuils 2026 (micro-BIC, régime réel, LMP) expliqués simplement, avec ce que ça change concrètement pour toi selon tes revenus. Pas de jargon, juste l\'essentiel.',
  },
  {
    id: 'revenus-journal-paiements-apr-2026',
    date: '2026-04-19',
    tag: 'nouveau',
    title: 'Revenus, journal de tous tes paiements',
    description: 'Tu peux maintenant enregistrer manuellement tes paiements reçus (virement, espèces, chèque…) en plus des paiements en ligne. Tout s\'affiche dans un seul journal clair avec le logement, le montant et le statut, encaissé ou en attente.',
  },
  {
    id: 'dashboard-resume-operationnel-apr-2026',
    date: '2026-04-19',
    tag: 'amélioration',
    title: 'Accueil, un vrai résumé de ton activité',
    description: 'La page d\'accueil te montre maintenant ce qui compte vraiment : tes séjours en cours, les arrivées de la semaine et les choses à ne pas oublier. Pratique pour démarrer la journée d\'un coup d\'œil.',
  },
  {
    id: 'calendrier-4-blocs-priorite-apr-2026',
    date: '2026-04-19',
    tag: 'amélioration',
    title: 'Calendrier, alertes classées par priorité',
    description: 'Les actions à faire sont maintenant regroupées par niveau d\'urgence : Critique, Urgent, Important, À faire. Tu sais immédiatement quoi traiter en premier.',
  },
  {
    id: 'calendrier-checklist-sejour-apr-2026',
    date: '2026-04-19',
    tag: 'nouveau',
    title: 'Calendrier, check-list par séjour',
    description: 'Chaque séjour a maintenant sa propre check-list : contrat envoyé, acompte reçu, ménage planifié, check-out… Coche au fur et à mesure et valide toute une étape d\'un seul clic.',
  },
  {
    id: 'calendrier-alertes-intelligentes-apr-2026',
    date: '2026-04-19',
    tag: 'nouveau',
    title: 'Calendrier, rappels automatiques par séjour',
    description: 'Le calendrier te signale discrètement les oublis : contrat non signé, solde non reçu, instructions pas encore envoyées… Les rappels s\'effacent automatiquement une fois la tâche cochée.',
  },
  {
    id: 'calendrier-categories-refonte-apr-2026',
    date: '2026-04-19',
    tag: 'amélioration',
    title: 'Calendrier, catégories simplifiées',
    description: 'Les types d\'événements ont été simplifiés pour coller à la réalité du terrain : Ménage, RDV et Tâche. Plus clair, plus rapide à utiliser.',
  },
  {
    id: 'calendrier-bug-date-apr-2026',
    date: '2026-04-19',
    tag: 'correction',
    title: 'Calendrier, création d\'événement corrigée',
    description: 'La date de fin s\'affichait parfois incorrectement à l\'ouverture du formulaire. C\'est corrigé.',
  },
  {
    id: 'voyageur-signalement-temoignage-apr-2026',
    date: '2026-04-12',
    tag: 'nouveau',
    title: 'Signaler ou témoigner directement depuis la fiche voyageur',
    description: 'Deux nouveaux boutons sur chaque fiche voyageur : "Signaler" pour remonter un incident (dégradation, arnaque, fête non autorisée…) et "Témoigner" pour laisser un retour positif. Les informations du voyageur sont pré-remplies automatiquement et le signalement est connecté à la base Sécurité Voyageur partagée avec la communauté.',
  },
  {
    id: 'guide-lcd-refonte-apr-2026',
    date: '2026-04-09',
    tag: 'amélioration',
    title: 'Refonte complète du Guide LCD',
    description: 'Le Guide LCD a été entièrement repensé : 4 profils distincts (Gîtes, Chambres d\'hôtes, Conciergeries, Réservation directe), 12 fiches détaillées avec indicateurs visuels (règle, avertissement, info) et mise à jour loi Le Meur 2025. Filtre par profil pour n\'afficher que ce qui te concerne.',
  },
  {
    id: 'gabarits-en-timing-apr-2026',
    date: '2026-04-08',
    tag: 'amélioration',
    title: 'Gabarits, version EN et filtres par moment',
    description: 'Les gabarits disposent d\'un toggle FR / EN pour accéder à la traduction anglaise. Filtre rapidement par moment : "Avant l\'arrivée", "Pendant le séjour" ou "Après le départ".',
  },
  {
    id: 'nouveautes-page-apr-2026',
    date: '2026-04-07',
    tag: 'nouveau',
    title: 'Page Nouveautés dédiée',
    description: 'Toutes les avancées de la plateforme sont désormais consultables sur une page dédiée. Retrouve l\'historique complet depuis le menu.',
  },
  {
    id: 'notif-system-apr-2026',
    date: '2026-04-06',
    tag: 'nouveau',
    title: 'Centre de notifications',
    description: 'Un panneau dédié pour suivre toutes les nouveautés et améliorations de la plateforme, tu es au bon endroit !',
  },
  {
    id: 'formations-catalog-apr-2026',
    date: '2026-04-01',
    tag: 'amélioration',
    title: '14 formations disponibles + filtres avancés',
    description: 'Le catalogue atteint 14 formations (maintenant 16) avec de nouveaux filtres par thème et par niveau.',
  },
  {
    id: 'theme-toggle-mar-2026',
    date: '2026-03-28',
    tag: 'amélioration',
    title: 'Mode clair / sombre amélioré',
    description: 'Le thème est maintenant mémorisé entre les sessions. Passe du mode sombre au mode clair en un clic depuis le header.',
  },
  {
    id: 'securite-traveler-mar-2026',
    date: '2026-03-20',
    tag: 'nouveau',
    title: 'Vérification voyageurs',
    description: 'La section Sécurité est en ligne. Vérifie l\'identité de tes voyageurs et consulte les signalements de la communauté avant chaque séjour.',
  },
  {
    id: 'gabarits-mar-2026',
    date: '2026-03-15',
    tag: 'nouveau',
    title: 'Bibliothèque de gabarits',
    description: 'Plus de 20 modèles de messages prêts à l\'emploi : check-in, check-out, bienvenue, avis clients… Copie en un clic et personnalise selon ton style.',
  },
  {
    id: 'formations-progress-mar-2026',
    date: '2026-03-01',
    tag: 'amélioration',
    title: 'Suivi de progression des formations',
    description: 'Ta progression est maintenant sauvegardée automatiquement. Reprends une formation là où tu t\'es arrêté, à tout moment.',
  },
  {
    id: 'partenaires-feb-2026',
    date: '2026-02-20',
    tag: 'nouveau',
    title: 'Espace partenaires Driing',
    description: 'Accède aux offres exclusives de nos partenaires sélectionnés pour les hôtes : outils de gestion, services de conciergerie et bien plus.',
  },
  {
    id: 'communaute-feb-2026',
    date: '2026-02-10',
    tag: 'nouveau',
    title: 'Accès aux groupes communautaires',
    description: 'Rejoins les groupes Facebook de la communauté Jason Marinho directement depuis ton dashboard. Réseau, entraide et partage d\'expériences.',
  },
  {
    id: 'auth-jan-2026',
    date: '2026-01-15',
    tag: 'important',
    title: 'Lancement de la plateforme membre',
    description: 'Bienvenue ! L\'espace membre Driing est officiellement lancé avec l\'authentification sécurisée, le profil personnalisé et l\'accès aux formations.',
  },
]
