// Extrait de CalendrierView.tsx (découpage sept. 2026, code inchangé).
// Styles inline du composant principal CalendrierView.
import type React from 'react'

export const s: Record<string, React.CSSProperties> = {
  pageTitle: { fontFamily: 'var(--font-fraunces), serif', fontSize: 'clamp(26px,3vw,38px)', fontWeight: 400, color: 'var(--text)', margin: '0 0 6px' },
  pageTitleSmall: {
    fontFamily: 'var(--font-fraunces), serif',
    fontSize: 'clamp(20px,2vw,26px)',
    fontWeight: 400,
    color: 'var(--text)',
    margin: 0,
    lineHeight: 1.2,
  },
  pageSub:   { fontSize: '14px', color: 'var(--text-2)', margin: 0 },
  // Header compact (titre + résumé 1 ligne)
  headerCompact: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    flexWrap: 'wrap' as const,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flexWrap: 'wrap' as const,
    flex: 1,
    minWidth: 0,
  },
  summaryRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap' as const,
  },
  summaryChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 10px',
    background: 'var(--surface)',
    border: '1px solid var(--border-2)',
    borderRadius: '8px',
    fontSize: '12px',
    color: 'var(--text-2)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap' as const,
    transition: 'border-color 0.15s',
  },
  summaryLabel: { fontSize: '11px', color: 'var(--text-muted)', textTransform: 'uppercase' as const, letterSpacing: '0.04em', fontWeight: 600 },
  summaryValue: { fontSize: '12.5px', color: 'var(--text)', fontWeight: 500 },
  summaryDays:  { fontSize: '11.5px', fontWeight: 600 },
  summaryOk: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 10px',
    background: 'rgba(16,185,129,0.08)',
    border: '1px solid rgba(16,185,129,0.2)',
    borderRadius: '8px',
    fontSize: '12px',
    color: 'var(--accent-text)',
    fontWeight: 500,
    whiteSpace: 'nowrap' as const,
  },
  summaryToggle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '5px 9px',
    background: 'transparent',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    fontSize: '11.5px',
    color: 'var(--text-2)',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  // Sync chip + panel
  syncChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 10px',
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    fontSize: '12px',
    color: 'var(--text-2)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap' as const,
  },
  syncDot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  syncPanel: {
    background: 'var(--surface)',
    border: '1px solid var(--border-2)',
    borderRadius: '12px',
    padding: '14px 16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
  },
  exportPanel: {
    position: 'absolute' as const,
    top: 'calc(100% + 8px)',
    right: 0,
    width: '340px',
    background: 'var(--bg-2)',
    border: '1px solid var(--border-2)',
    borderRadius: '12px',
    padding: '14px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
    zIndex: 50,
    boxShadow: '0 12px 32px rgba(0,0,0,0.35)',
  },
  exportHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  exportTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--text)',
    fontFamily: 'var(--font-fraunces), serif',
  },
  exportClose: {
    width: '22px', height: '22px',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    background: 'transparent', border: 'none', borderRadius: '6px',
    color: 'var(--text-muted)', cursor: 'pointer',
  },
  exportDesc: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    lineHeight: 1.45,
    margin: 0,
  },
  exportUrlRow: {
    display: 'flex', gap: '6px', alignItems: 'stretch',
  },
  exportUrlInput: {
    flex: 1, minWidth: 0,
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    padding: '8px 10px',
    fontSize: '11px',
    fontFamily: 'ui-monospace, SFMono-Regular, monospace',
    color: 'var(--text-2)',
  },
  exportCopyBtn: {
    display: 'inline-flex', alignItems: 'center', gap: '4px',
    padding: '0 12px',
    background: 'var(--accent-bg-2)',
    border: '1px solid var(--accent-border)',
    color: 'var(--accent-text)',
    borderRadius: '8px',
    fontSize: '11px', fontWeight: 600,
    cursor: 'pointer',
    flexShrink: 0,
  },
  exportCopyBtnOk: {
    background: 'rgba(16,185,129,0.15)',
    borderColor: 'rgba(16,185,129,0.4)',
    color: 'var(--accent-text)',
  },
  exportPrimaryBtn: {
    width: '100%',
    background: 'var(--accent-text)',
    color: 'var(--bg)',
    border: 'none', borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '13px', fontWeight: 600,
    cursor: 'pointer',
  },
  exportSecondaryBtn: {
    display: 'inline-flex', alignItems: 'center', gap: '4px',
    alignSelf: 'flex-start',
    padding: '6px 10px',
    background: 'transparent',
    border: '1px solid var(--border)',
    color: 'var(--text-muted)',
    borderRadius: '7px',
    fontSize: '11px',
    cursor: 'pointer',
  },
  syncPanelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  syncPanelTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--text)',
    fontFamily: 'var(--font-fraunces), serif',
  },
  syncAllBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '5px 11px',
    fontSize: '11.5px',
    fontWeight: 600,
    color: 'var(--bg)',
    background: 'var(--accent-text)',
    border: 'none',
    borderRadius: '7px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  syncFeedsList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '5px',
  },
  syncFeedItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    background: 'var(--bg-2)',
    border: '1px solid var(--border)',
    borderRadius: '7px',
    fontSize: '12px',
    color: 'var(--text-2)',
  },
  syncOk: {
    fontSize: '12px',
    color: 'var(--accent-text)',
    background: 'rgba(16,185,129,0.08)',
    padding: '6px 10px',
    borderRadius: '7px',
  },
  syncErr: {
    fontSize: '12px',
    color: 'var(--danger)',
    background: 'rgba(239,68,68,0.08)',
    padding: '6px 10px',
    borderRadius: '7px',
  },
  syncEmpty: {
    fontSize: '11.5px',
    color: 'var(--text-muted)',
    margin: 0,
    fontStyle: 'italic' as const,
    lineHeight: 1.5,
  },
  // Topbar icon button (lightning toggle)
  topbarIconBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    minWidth: '32px',
    padding: '0 9px',
    height: '32px',
    fontSize: '12.5px',
    fontWeight: 600,
    background: 'transparent',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--text-2)',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  topbarIconBtnActive: {
    background: 'var(--accent-bg)',
    borderColor: 'var(--accent-border)',
    color: 'var(--accent-text)',
  },
  quickAddClose: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '26px',
    background: 'transparent',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    flexShrink: 0,
  },
  root: {
    padding: '20px var(--dash-page-px) 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    minHeight: 0,
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    flexWrap: 'wrap',
  },
  monthNav: { display: 'flex', alignItems: 'center', gap: 'var(--s-3)' },
  monthTitle: {
    fontSize: 'var(--t-xl)',
    fontWeight: 400,
    color: 'var(--text)',
    margin: 0,
    letterSpacing: 'var(--ls-tight)',
    fontFamily: 'var(--font-fraunces), serif',
    minWidth: '220px',
    textAlign: 'center' as const,
  },
  navBtn: {
    width: '38px', height: '38px',
    padding: 0,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    borderRadius: 'var(--r-sm)',
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    color: 'var(--text-2)',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'background var(--d-base) var(--ease-smooth), border-color var(--d-base) var(--ease-smooth), color var(--d-base) var(--ease-smooth), transform var(--d-base) var(--ease-spring)',
  },
  todayBtn: {
    padding: '9px 18px',
    borderRadius: 'var(--r-sm)',
    fontSize: 'var(--t-sm)',
    fontWeight: 600,
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    color: 'var(--text-2)',
    cursor: 'pointer',
    transition: 'background var(--d-base) var(--ease-smooth), border-color var(--d-base) var(--ease-smooth), color var(--d-base) var(--ease-smooth)',
  },
  addBtn: {
    display: 'flex', alignItems: 'center', gap: 'var(--s-2)',
    padding: '10px 20px',
    fontSize: 'var(--t-sm)', fontWeight: 600,
    borderRadius: 'var(--r-md)',
    border: 'none',
    cursor: 'pointer',
    transition: 'background var(--d-base) var(--ease-smooth), transform var(--d-base) var(--ease-spring), box-shadow var(--d-base) var(--ease-smooth)',
  },
  layout: {
    display: 'flex',
    position: 'relative' as const,
    background: 'var(--surface)',
    border: '1px solid var(--border-2)',
    borderRadius: '16px',
    overflow: 'hidden',
    minHeight: '640px',
  },
  gridWrap: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' },
  dayHeaders: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', borderBottom: '1px solid var(--border-2)', background: 'var(--bg-2)' },
  dayHeader: {
    padding: '10px 8px',
    textAlign: 'center',
    fontSize: '11px', fontWeight: 600,
    letterSpacing: '0.7px',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
  },
  grid: { flex: 1, display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)' },
  cell: {
    minHeight: '108px',
    padding: 'var(--s-2)',
    borderRight: '1px solid var(--border)',
    borderBottom: '1px solid var(--border)',
    display: 'flex', flexDirection: 'column' as const, gap: 'var(--s-1)',
    outlineOffset: '-1px',
    transition: 'background var(--d-base) var(--ease-smooth)',
  },
  cellTop: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    marginBottom: 'var(--s-1)',
  },
  dayNum: { fontSize: 'var(--t-sm)', fontWeight: 600, lineHeight: 1, fontVariantNumeric: 'tabular-nums' as const },
  dotRow: { display: 'flex', gap: '3px', alignItems: 'center' },
  dot: { width: '6px', height: '6px', borderRadius: '50%', flexShrink: 0 },
  pillWrap: { display: 'flex', flexDirection: 'column' as const, gap: '3px' },
  pill: {
    display: 'flex', alignItems: 'center',
    padding: '3px 7px 3px 6px',
    borderRadius: 'var(--r-xs)',
    borderLeft: '3px solid',
    overflow: 'hidden' as const,
    transition: 'transform var(--d-fast) var(--ease-smooth), background var(--d-base) var(--ease-smooth)',
  },
  pillText: {
    fontSize: 'var(--t-xs)', fontWeight: 500, color: 'var(--text-2)',
    overflow: 'hidden' as const, textOverflow: 'ellipsis' as const, whiteSpace: 'nowrap' as const, maxWidth: '100%',
  },
  extraChip: { fontSize: 'var(--t-xs)', fontWeight: 600, color: 'var(--text-muted)', padding: '1px 5px' },

  // side: drawer slidant à droite (position absolute pour libérer la grille)
  side: {
    position: 'absolute' as const,
    right: 0, top: 0, bottom: 0,
    width: '340px',
    background: 'var(--bg)',
    borderLeft: '1px solid var(--border)',
    display: 'flex', flexDirection: 'column',
    overflowY: 'auto',
    zIndex: 5,
    transition: 'transform 0.25s ease, box-shadow 0.25s ease',
  },
  sideHead: {
    padding: '18px 18px 14px',
    borderBottom: '1px solid var(--border)',
    display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '8px',
    position: 'sticky', top: 0,
    background: 'var(--bg)', zIndex: 1,
  },
  sideHeadLeft: { display: 'flex', flexDirection: 'column', gap: '1px' },
  sideDow: {
    fontSize: '16px', fontWeight: 600, color: 'var(--text)',
    fontFamily: 'var(--font-fraunces), serif',
    textTransform: 'capitalize', letterSpacing: '-0.2px',
  },
  sideDate: { fontSize: '13px', color: 'var(--text-muted)', textTransform: 'capitalize' },
  addDayBtn: {
    width: '30px', height: '30px',
    borderRadius: '8px',
    border: '1px solid var(--border-2)',
    background: 'var(--surface)',
    color: 'var(--text-2)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer', flexShrink: 0, padding: 0,
  },

  // form
  form: {
    padding: '16px',
    display: 'flex', flexDirection: 'column', gap: '10px',
    borderBottom: '1px solid var(--border)',
  },
  fInput: {
    width: '100%', padding: '11px 14px',
    fontSize: '15px', fontWeight: 500, borderRadius: '10px',
  },
  fLabel: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--text-3)',
    letterSpacing: '0.4px',
    textTransform: 'uppercase' as const,
    marginBottom: '5px',
  },
  dateRow: {
    display: 'grid', gridTemplateColumns: '1fr auto 1fr',
    gap: '4px', alignItems: 'center',
  },
  rowArrow: {
    color: 'var(--text-muted)', fontSize: '12px',
    flexShrink: 0, textAlign: 'center',
  },
  catRow: { display: 'flex', flexWrap: 'wrap', gap: '6px' },
  catChip: {
    padding: '6px 12px', borderRadius: '100px',
    fontSize: '12px', fontWeight: 600, cursor: 'pointer',
    display: 'flex', alignItems: 'center', gap: '6px',
    transition: 'all 0.15s',
  },
  fTextarea: {
    width: '100%', padding: '10px 14px',
    fontSize: '13px', borderRadius: '10px',
    resize: 'vertical' as const, minHeight: '72px',
  },
  fCancel: { padding: '9px 14px', fontSize: '13px', borderRadius: '9px' },
  fSave:   { padding: '9px 18px', fontSize: '13px', fontWeight: 600, border: 'none', cursor: 'pointer', borderRadius: '9px' },

  // events
  evtList: { padding: '12px', display: 'flex', flexDirection: 'column', gap: '8px', flex: 1 },
  evtCard: {
    padding: '12px 14px', borderRadius: '10px',
    border: '1px solid var(--border)',
    background: 'var(--bg-2)',
    display: 'flex', flexDirection: 'column', gap: '5px',
  },
  evtCardTop: {
    display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '8px',
  },
  evtTitle: { fontSize: '13px', fontWeight: 600, color: 'var(--text)', lineHeight: 1.35 },
  spanBadge: {
    fontSize: '11px', fontWeight: 500,
    color: 'var(--accent-text)',
    background: 'var(--accent-bg)',
    padding: '2px 8px', borderRadius: '100px',
  },
  evtTime: {
    display: 'flex', alignItems: 'center', gap: '4px',
    fontSize: '12px', color: 'var(--text-muted)', fontWeight: 500,
  },
  catLabel: { fontSize: '11px', fontWeight: 600, letterSpacing: '0.4px', textTransform: 'uppercase' },
  evtDesc: { fontSize: '12px', color: 'var(--text-2)', margin: '2px 0 0', lineHeight: 1.5, whiteSpace: 'pre-line', overflowWrap: 'anywhere' },
  completeBox: { display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '6px', padding: '10px 12px', borderRadius: '10px', background: 'rgba(255,213,107,0.14)', border: '1px solid rgba(255,213,107,0.4)' },
  completeText: { margin: 0, fontSize: '12.5px', color: 'var(--text-2)', lineHeight: 1.45 },
  completeBtn: { display: 'inline-flex', alignItems: 'center', gap: '6px', alignSelf: 'flex-start', padding: '7px 12px', borderRadius: '9px', border: 'none', background: 'var(--accent-text)', color: 'var(--bg)', fontSize: '12.5px', fontWeight: 700, fontFamily: 'inherit', cursor: 'pointer' },
  linkedChip: { display: 'inline-flex', alignItems: 'center', gap: '5px', alignSelf: 'flex-start', marginTop: '4px', fontSize: '11.5px', fontWeight: 600, color: 'var(--accent-text)', background: 'var(--accent-bg)', border: '1px solid var(--accent-border)', padding: '3px 9px', borderRadius: '100px' },
  autoBadge: {
    fontSize: '10px', fontWeight: 700, letterSpacing: '0.5px',
    padding: '2px 7px', borderRadius: '100px', flexShrink: 0, alignSelf: 'flex-start',
  },
  iconBtn: {
    width: '26px', height: '26px', borderRadius: '7px',
    border: '1px solid var(--border)',
    background: 'var(--surface)', color: 'var(--text-3)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer', padding: 0, flexShrink: 0,
  },
  emptyState: {
    display: 'flex', flexDirection: 'column',
    alignItems: 'center', justifyContent: 'center',
    flex: 1, padding: '32px 16px', textAlign: 'center',
  },

  // À traiter, liste compacte
  alertList: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  alertHeader: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '8px 14px',
    borderBottom: '1px solid var(--border)',
    gap: '12px',
  },
  alertHeaderLabel: {
    display: 'inline-flex', alignItems: 'center', gap: '8px',
    fontSize: '11px', fontWeight: 700,
    color: 'var(--text-2)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.6px',
  },
  alertHeaderCount: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    minWidth: '18px', height: '18px', padding: '0 5px',
    fontSize: '10px', fontWeight: 700,
    background: 'var(--accent-bg)',
    color: 'var(--accent-text)',
    borderRadius: '9px',
  },
  alertHeaderHint: {
    fontSize: '10px', fontWeight: 400,
    color: 'var(--text-muted)',
  },
  alertItems: {
    display: 'flex', flexDirection: 'column' as const,
  },
  alertItem: {
    display: 'flex', alignItems: 'stretch',
    borderTop: '1px solid var(--border)',
    borderLeft: '3px solid transparent',
    transition: 'background 0.12s',
  },
  alertItemMain: {
    flex: 1,
    display: 'flex', alignItems: 'center', gap: '8px',
    padding: '8px 12px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    textAlign: 'left' as const,
    minWidth: 0,
    color: 'var(--text-2)',
    fontFamily: 'inherit',
  },
  alertDot: {
    width: '7px', height: '7px', borderRadius: '50%',
    flexShrink: 0,
  },
  alertLogement: {
    fontSize: '12.5px', fontWeight: 600,
    color: 'var(--text)',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const,
    maxWidth: '180px',
    flexShrink: 0,
  },
  alertSep: {
    color: 'var(--text-muted)',
    fontSize: '11px',
    flexShrink: 0,
  },
  alertLabel: {
    fontSize: '12px', fontWeight: 400,
    color: 'var(--text-2)',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const,
    flex: 1,
    minWidth: 0,
  },
  alertDays: {
    fontSize: '11px', fontWeight: 600,
    flexShrink: 0,
    marginLeft: 'auto',
  },
  alertCheckBtn: {
    width: '36px',
    background: 'transparent',
    border: 'none',
    borderLeft: '1px solid var(--border)',
    color: 'var(--accent-text)',
    fontSize: '14px', fontWeight: 700,
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'all 0.12s',
    fontFamily: 'inherit',
  },
  alertGabaritBtn: {
    display: 'inline-flex', alignItems: 'center', gap: '4px',
    padding: '4px 10px',
    background: 'var(--accent-bg-2)',
    border: '1px solid var(--accent-border-2)',
    borderRadius: '999px',
    color: 'var(--accent-text)',
    fontSize: '11px', fontWeight: 600,
    textDecoration: 'none',
    cursor: 'pointer',
    flexShrink: 0,
    fontFamily: 'inherit',
    marginRight: '6px',
  },
  alertOk: {
    display: 'flex', alignItems: 'center', gap: '10px',
    padding: '10px 14px',
    background: 'rgba(16,185,129,0.07)',
    border: '1px solid rgba(16,185,129,0.22)',
    borderRadius: '12px',
    fontSize: '12px', fontWeight: 500,
    color: 'var(--accent-text)',
  },
  alertOkDot: {
    width: '8px', height: '8px', borderRadius: '50%',
    background: 'var(--accent-text)',
    boxShadow: '0 0 0 4px rgba(16,185,129,0.18)',
  },

  // Prochain événement
  nextWrap: {
    display: 'flex', alignItems: 'center', gap: '12px',
    flexWrap: 'wrap' as const,
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderLeft: '3px solid',
    borderRadius: '12px',
    padding: '10px 14px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    color: 'var(--text-2)',
    textAlign: 'left' as const,
    width: '100%',
  },
  nextLabel: {
    fontSize: '10px', fontWeight: 700, letterSpacing: '0.6px',
    textTransform: 'uppercase' as const,
    color: 'var(--text-muted)',
    flexShrink: 0,
  },
  nextMain: {
    display: 'inline-flex', alignItems: 'baseline', gap: '6px',
    flex: 1, minWidth: 0,
  },
  nextTitle: {
    fontSize: '13px', fontWeight: 600,
    color: 'var(--text)',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const,
  },
  nextSub: {
    fontSize: '12px', fontWeight: 400,
    color: 'var(--text-muted)',
  },
  nextDays: {
    fontSize: '12px', fontWeight: 600,
    flexShrink: 0,
  },

  // View toggle
  viewToggle: {
    display: 'inline-flex', alignItems: 'center', gap: '2px',
    padding: '3px',
    background: 'var(--surface)',
    border: '1px solid var(--border-2)',
    borderRadius: '10px',
  },
  viewBtn: {
    display: 'inline-flex', alignItems: 'center', gap: '6px',
    padding: '6px 12px',
    fontSize: '12.5px', fontWeight: 500,
    color: 'var(--text-2)',
    background: 'transparent',
    border: 'none',
    borderRadius: '7px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.15s',
  },
  viewBtnActive: {
    background: 'var(--accent-bg)',
    color: 'var(--accent-text)',
  },

  // Filter bar
  filterBar: {
    display: 'flex', alignItems: 'center', gap: '12px',
    flexWrap: 'wrap' as const,
  },
  filterChips: {
    display: 'flex', gap: '6px', flexWrap: 'wrap' as const,
  },
  filterChip: {
    padding: '6px 12px',
    fontSize: '12px', fontWeight: 500,
    color: 'var(--text-2)',
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: '100px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.15s',
  },
  filterChipActive: {
    background: 'var(--accent-bg)',
    borderColor: 'var(--accent-border)',
    color: 'var(--accent-text)',
  },
  searchWrap: {
    position: 'relative' as const,
    flex: '1 1 220px',
    minWidth: '180px',
    maxWidth: '320px',
  },
  searchIcon: {
    position: 'absolute' as const,
    left: '12px', top: '50%',
    transform: 'translateY(-50%)',
    color: 'var(--text-muted)',
    display: 'flex',
    pointerEvents: 'none' as const,
  },
  searchInput: {
    width: '100%',
    padding: '8px 32px 8px 32px',
    fontSize: '12.5px',
    fontFamily: 'inherit',
    color: 'var(--text)',
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: '9px',
    outline: 'none',
  },
  searchClear: {
    position: 'absolute' as const,
    right: '6px', top: '50%',
    transform: 'translateY(-50%)',
    width: '20px', height: '20px',
    borderRadius: '50%',
    border: 'none',
    background: 'var(--border)',
    color: 'var(--text-2)',
    fontSize: '14px',
    cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    lineHeight: 1,
    fontFamily: 'inherit',
  },

  // Quick add
  quickAddWrap: {
    display: 'flex', alignItems: 'center', gap: '10px',
    padding: '4px 6px 4px 14px',
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: '11px',
    transition: 'border-color 0.15s',
  },
  quickAddIcon: {
    fontSize: '13px',
    color: 'var(--accent-text)',
    flexShrink: 0,
  },
  quickAddInput: {
    flex: 1,
    minWidth: 0,
    padding: '8px 0',
    fontSize: '12.5px',
    fontFamily: 'inherit',
    color: 'var(--text)',
    background: 'transparent',
    border: 'none',
    outline: 'none',
  },
  quickAddBtn: {
    padding: '6px 14px',
    fontSize: '12px', fontWeight: 600,
    color: 'var(--bg)',
    background: 'var(--accent-text)',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    flexShrink: 0,
  },

  // Sources synchronisées (iCal feeds)
  sourcesWrap: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  sourcesToggle: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    width: '100%',
    padding: '8px 14px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    color: 'var(--text-2)',
  },
  sourcesToggleLeft: {
    display: 'inline-flex', alignItems: 'center', gap: '10px',
  },
  sourcesDots: {
    display: 'inline-flex', alignItems: 'center', gap: '4px',
  },
  sourcesDot: {
    width: '8px', height: '8px', borderRadius: '50%',
  },
  sourcesLabel: {
    fontSize: '12px', fontWeight: 500,
    color: 'var(--text-2)',
  },
  sourcesCount: {
    color: 'var(--text-muted)',
    fontWeight: 400,
  },
  sourcesChevron: {
    color: 'var(--text-muted)',
    display: 'flex',
    transition: 'transform 0.18s',
  },
  sourcesList: {
    borderTop: '1px solid var(--border)',
    padding: '10px 14px',
    display: 'flex', flexDirection: 'column' as const, gap: '6px',
  },
  sourceItem: {
    display: 'flex', alignItems: 'center', gap: '10px',
    fontSize: '12px',
  },
  sourceName: {
    fontWeight: 500,
    color: 'var(--text-2)',
  },
  sourceCount: {
    color: 'var(--text-3)',
    marginLeft: 'auto',
  },
  sourceSync: {
    color: 'var(--text-muted)',
    fontSize: '11px',
  },

  // Mini-stats header
  miniStats: {
    display: 'flex', flexWrap: 'wrap' as const,
    gap: '16px 24px',
    marginTop: '10px',
  },
  miniStat: {
    display: 'flex', alignItems: 'baseline', gap: '6px',
    fontSize: '13px',
    color: 'var(--text-2)',
  },
  miniStatNum: {
    fontFamily: 'var(--font-fraunces), serif',
    fontSize: '17px', fontWeight: 500,
    color: 'var(--text)',
  },
  miniStatLabel: {
    fontSize: '12px', fontWeight: 400,
    color: 'var(--text-muted)',
  },
  miniStatSep: {
    color: 'var(--border-2)',
    margin: '0 4px',
  },
  // Legend
  legend: {
    display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' as const,
    padding: '9px 12px',
    borderTop: '1px solid var(--border-2)',
    background: 'var(--bg-2)',
  },
  legendChip: {
    display: 'inline-flex', alignItems: 'center', gap: '5px',
    padding: '3px 10px',
    fontSize: '11px', fontWeight: 500,
    color: 'var(--text-2)',
    background: 'transparent',
    border: '1px solid var(--border)',
    borderRadius: '100px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.12s',
    whiteSpace: 'nowrap' as const,
  },
  legendChipActive: {
    background: 'var(--surface)',
    borderColor: 'var(--border-2)',
    fontWeight: 600,
  },
  legendDot: {
    width: '7px', height: '7px', borderRadius: '50%', flexShrink: 0,
  },
  legendClear: {
    fontSize: '11px', fontWeight: 500,
    color: 'var(--text-muted)',
    background: 'transparent', border: 'none',
    cursor: 'pointer', fontFamily: 'inherit',
    padding: '3px 6px',
    marginLeft: '2px',
  },
  sourcesBadge: {
    position: 'absolute' as const,
    top: '-3px', right: '-3px',
    minWidth: '14px', height: '14px',
    padding: '0 3px',
    background: 'var(--accent-text)',
    color: 'var(--bg)',
    borderRadius: '7px',
    fontSize: '9px', fontWeight: 700,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    lineHeight: 1,
    fontFamily: 'inherit',
  },
  sourcesRow: {
    display: 'flex', alignItems: 'center', gap: '10px',
    padding: '9px 11px',
    background: 'transparent',
    border: '1px solid var(--border)',
    borderRadius: 'var(--r-md)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: '13px',
    width: '100%',
    transition: 'all 0.12s',
  },

  // ── KPIs compacts mobile (3 cartes) ──
  mobKpi: {
    display: 'flex', flexDirection: 'column' as const,
    alignItems: 'flex-start',
    gap: 2,
    padding: '10px 12px',
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 12,
  },
  mobKpiNum: {
    fontFamily: 'var(--font-fraunces), serif',
    fontSize: 20, fontWeight: 600,
    color: 'var(--text)',
    lineHeight: 1,
  },
  mobKpiLabel: {
    fontSize: 10.5,
    color: 'var(--text-3)',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.6,
    fontWeight: 500,
  },
}
