// Registre de tous les articles du blog.
// Ajouté automatiquement par scripts/generate-article.mjs pour les nouveaux articles.
export const articles = [
  { slug: 'optimiser-annonce-airbnb',                              categorySlug: 'visibilite',     date: '2025-03-01', readTime: 5,  title: 'Optimiser son annonce Airbnb : les 8 éléments qui font vraiment la différence' },
  { slug: 'tarification-dynamique-lcd',                            categorySlug: 'revenus',        date: '2025-03-01', readTime: 7,  title: 'Tarification dynamique en location courte durée : par où commencer' },
  { slug: 'messages-airbnb-automatiser',                           categorySlug: 'automatisation', date: '2025-03-01', readTime: 4,  title: 'Les 5 messages Airbnb à automatiser absolument dès cette semaine' },
  { slug: 'google-my-business-hotes-lcd',                          categorySlug: 'visibilite',     date: '2025-03-01', readTime: 6,  title: 'Pourquoi Google My Business est indispensable pour les hôtes LCD en 2025' },
  { slug: 'reservation-directe-sans-commission',                   categorySlug: 'revenus',        date: '2025-03-01', readTime: 8,  title: 'Réservation directe sans commission : comment se lancer sans site web' },
  { slug: 'creer-conciergerie-airbnb-2025',                        categorySlug: 'conciergerie',   date: '2025-03-01', readTime: 10, title: 'Créer sa conciergerie Airbnb en 2025 : les étapes essentielles pour démarrer' },
  { slug: 'obtenir-avis-5-etoiles-airbnb',                         categorySlug: 'experience',     date: '2025-03-01', readTime: 5,  title: 'Comment obtenir plus d\'avis 5 étoiles sur Airbnb sans harceler tes voyageurs' },
  { slug: 'location-courte-duree-impots-france',                   categorySlug: 'fiscalite',      date: '2025-03-01', readTime: 9,  title: 'Location courte durée et impôts : ce que tout hôte doit savoir en France' },
  { slug: 'outils-gerer-location-courte-duree-2025',               categorySlug: 'automatisation', date: '2025-03-01', readTime: 6,  title: 'Les 7 outils indispensables pour gérer sa location courte durée en 2025' },
  { slug: 'livret-accueil-digital-hotes-lcd',                      categorySlug: 'experience',     date: '2025-03-01', readTime: 4,  title: 'Livret d\'accueil digital : pourquoi c\'est devenu indispensable pour les hôtes LCD' },
  { slug: 'reglementation-lcd-france-2026',                        categorySlug: 'reglementation', date: '2025-11-01', readTime: 8,  title: 'Réglementation LCD France 2026 : tout ce qui change pour les hôtes' },
  { slug: 'driing-plateforme-vacances-sans-commissions',           categorySlug: 'driing',         date: '2025-03-01', readTime: 6,  title: 'Driing : la plateforme de vacances sans commissions qui change la donne' },
  { slug: 'airbnb-vs-booking-com-location-courte-duree',           categorySlug: 'visibilite',     date: '2026-03-25', readTime: 8,  title: 'Airbnb vs Booking.com : lequel choisir pour ton logement LCD ?' },
  { slug: 'photographier-logement-location-courte-duree-smartphone', categorySlug: 'visibilite',   date: '2026-03-25', readTime: 7,  title: 'Comment photographier son logement LCD soi-même (sans matériel pro)' },
  { slug: 'attirer-teletravailleur-nomade-digital-location-courte-duree', categorySlug: 'revenus', date: '2026-03-25', readTime: 7,  title: 'Télétravail et LCD : comment attirer les nomades digitaux dans ton logement' },
  { slug: 'gerer-mauvais-avis-airbnb-reponse-hote',                categorySlug: 'experience',     date: '2026-03-25', readTime: 6,  title: 'Comment gérer un mauvais avis sur Airbnb sans perdre ton classement' },
  { slug: 'declarer-activite-location-courte-duree-france-demarches', categorySlug: 'reglementation', date: '2026-03-25', readTime: 9, title: 'Déclarer son activité LCD en France : les démarches administratives à connaître' },
  { slug: 'gerer-voyageurs-difficiles-location-courte-duree',      categorySlug: 'experience',     date: '2026-03-25', readTime: 7,  title: 'Voyageurs difficiles en LCD : comment prévenir et gérer les situations problématiques' },
  { slug: 'site-reservation-directe-location-courte-duree',        categorySlug: 'revenus',        date: '2026-03-25', readTime: 8,  title: 'Créer son premier site de réservation directe en LCD : par où commencer' },
  { slug: 'conciergerie-airbnb-faire-appel-choisir',               categorySlug: 'conciergerie',   date: '2026-03-25', readTime: 7,  title: 'Conciergerie Airbnb : faut-il en faire appel à une et comment bien la choisir ?' },
  { slug: 'titre-annonce-airbnb-optimiser-clics-visibilite',       categorySlug: 'visibilite',     date: '2026-03-25', readTime: 6,  title: 'Titre d\'annonce Airbnb : comment écrire un titre qui fait cliquer' },
  { slug: 'tarification-dynamique-pricelabs-wheelhouse-beyond-comparatif', categorySlug: 'revenus', date: '2026-03-25', readTime: 8, title: 'Tarification dynamique en LCD : Pricelabs, Wheelhouse ou Beyond — lequel choisir ?' },
  { slug: 'livret-accueil-digital-creer-location-courte-duree',    categorySlug: 'experience',     date: '2026-03-25', readTime: 7,  title: 'Livret d\'accueil digital : pourquoi c\'est devenu indispensable et comment en créer un' },
  { slug: 'fixer-prix-minimum-airbnb-lcd',                         categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Comment fixer son prix minimum sur Airbnb sans se brader' },
  { slug: 'erreurs-debutant-location-courte-duree-premier-logement', categorySlug: 'revenus',      date: '2026-03-25', readTime: 9,  title: 'Premier logement LCD : les 10 erreurs à éviter quand on se lance' },
  { slug: 'location-directe-pourquoi-saffranchir-plateformes',     categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Location en direct : pourquoi de plus en plus d\'hôtes s\'affranchissent des plateformes' },
  { slug: 'premieres-reservations-directes-sans-audience-site-web', categorySlug: 'revenus',       date: '2026-03-25', readTime: 7,  title: 'Comment obtenir ses premières réservations directes sans audience ni site web' },
  { slug: 'base-voyageurs-fideles-location-directe-durable',       categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Construire une base de voyageurs fidèles : la clé de la location directe durable' },
  { slug: 'fixer-prix-reservation-directe-location-courte-duree',  categorySlug: 'revenus',        date: '2026-03-25', readTime: 6,  title: 'Comment fixer son prix pour la réservation directe : ni trop cher, ni bradé' },
  { slug: 'securiser-paiement-reservation-directe-sans-airbnb',    categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Réservation directe : comment sécuriser le paiement et protéger ton logement sans Airbnb' },
  { slug: 'instagram-hotes-lcd-attirer-voyageurs-reservations-directes', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Instagram pour hôtes LCD : comment attirer des voyageurs directement depuis les réseaux' },
  { slug: 'politique-annulation-location-directe-hote',            categorySlug: 'revenus',        date: '2026-03-25', readTime: 6,  title: 'Gérer les annulations en location directe : quelle politique adopter et comment l\'appliquer' },
  { slug: 'description-logement-convertit-reservation-directe',    categorySlug: 'visibilite',     date: '2026-03-25', readTime: 7,  title: 'Rédiger une description de logement qui convertit en réservation directe' },
  { slug: 'google-my-business-reservations-directes-hotes-lcd',    categorySlug: 'visibilite',     date: '2026-03-25', readTime: 8,  title: 'Google My Business pour hôtes LCD : le levier gratuit qui génère des réservations directes' },
  { slug: 'pms-logiciel-gestion-location-courte-duree-debutant',   categorySlug: 'automatisation', date: '2026-03-25', readTime: 8,  title: 'PMS pour débutant : quel logiciel choisir selon ton profil LCD ?' },
  { slug: 'mesurer-performance-canal-reservation-directe-kpi',     categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Mesurer la performance de ton canal de réservation directe : les chiffres qui comptent vraiment' },
  { slug: 'verification-voyageurs-avant-accepter-reservation-lcd', categorySlug: 'experience',     date: '2026-03-25', readTime: 6,  title: 'Comment vérifier un voyageur avant d\'accepter sa réservation en LCD' },
  { slug: 'gabarits-messages-lcd-hotes-templates',                 categorySlug: 'automatisation', date: '2026-03-25', readTime: 5,  title: 'Gabarits de messages LCD : arrête de réécrire les mêmes messages à chaque voyageur' },
  { slug: 'communaute-lcd-groupes-hotes-entraide-facebook',        categorySlug: 'ressources',     date: '2026-03-25', readTime: 6,  title: 'Communauté LCD : pourquoi les meilleurs hôtes ne travaillent pas seuls' },
  { slug: 'partenaires-lcd-outils-valides-terrain-hotes',          categorySlug: 'ressources',     date: '2026-03-25', readTime: 6,  title: 'Partenaires LCD : pourquoi les outils que tu utilises méritent d\'être validés avant d\'y mettre ton argent' },
  { slug: 'formation-google-my-business-lcd-contenu',              categorySlug: 'visibilite',     date: '2026-03-25', readTime: 5,  title: 'Formation Google My Business pour la LCD : ce qu\'elle contient et pourquoi la suivre' },
  { slug: 'chambres-hotes-plateforme-jason-marinho-ressources',    categorySlug: 'ressources',     date: '2026-03-25', readTime: 6,  title: 'Chambres d\'hôtes : comment la plateforme Jason Marinho t\'aide à développer ton activité' },
  { slug: 'conciergeries-lcd-ressources-plateforme-jason-marinho', categorySlug: 'conciergerie',   date: '2026-03-25', readTime: 6,  title: 'Conciergeries LCD : les ressources de la plateforme qui font gagner du temps à grande échelle' },
  { slug: 'formations-lcd-disponibles-plateforme-jason-marinho',   categorySlug: 'ressources',     date: '2026-03-25', readTime: 5,  title: 'Formations LCD disponibles sur la plateforme : ce que tu peux suivre maintenant et ce qui arrive' },
  { slug: 'pourquoi-creer-compte-plateforme-jason-marinho',        categorySlug: 'ressources',     date: '2026-03-25', readTime: 5,  title: 'Pourquoi créer un compte gratuit sur la plateforme Jason Marinho dès maintenant' },
  { slug: 'checklist-menage-professionnelle-location-courte-duree', categorySlug: 'experience',    date: '2026-03-25', readTime: 6,  title: 'Checklist ménage professionnelle pour hôte LCD (+ gabarit à télécharger)' },
  { slug: 'appel-decouverte-jason-marinho-accompagnement-lcd',     categorySlug: 'ressources',     date: '2026-03-25', readTime: 5,  title: 'L\'appel découverte Jason Marinho : à qui ça s\'adresse et ce qu\'on y fait en 30 minutes' },
  { slug: 'amenager-logement-location-courte-duree-petit-budget',  categorySlug: 'experience',     date: '2026-03-25', readTime: 8,  title: 'Aménager son logement pour la LCD avec un petit budget' },
  { slug: 'booking-com-hotes-location-courte-duree-guide',         categorySlug: 'visibilite',     date: '2026-03-25', readTime: 7,  title: 'Booking.com pour les hôtes LCD : tout ce qu\'il faut savoir avant de s\'inscrire' },
  { slug: 'check-in-location-courte-duree-boite-a-cles-serrure-connectee', categorySlug: 'automatisation', date: '2026-03-25', readTime: 7, title: 'Check-in en LCD : accueil en personne, boîte à clés ou serrure connectée ?' },
  { slug: 'assurance-location-courte-duree-airbnb-couverture',     categorySlug: 'reglementation', date: '2026-03-25', readTime: 8,  title: 'Assurance en location courte durée : ce que couvre vraiment Airbnb (et ce qu\'il ne couvre pas)' },
  { slug: 'basse-saison-location-courte-duree-strategies-reservations', categorySlug: 'revenus',   date: '2026-03-25', readTime: 8,  title: 'Basse saison en LCD : 7 stratégies concrètes pour remplir ton calendrier' },
]

export const CATEGORIES = {
  revenus:        { label: 'Revenus',         section: 'Revenus',               barColor: '#E8A020',   catColor: '#B06010'    },
  visibilite:     { label: 'Visibilité',      section: 'Visibilité',            barColor: 'var(--g)',  catColor: 'var(--g)'   },
  experience:     { label: 'Expérience',      section: 'Expérience voyageur',   barColor: '#D97706',   catColor: '#92400E'    },
  ressources:     { label: 'Ressources',      section: 'Ressources',            barColor: '#8B5CF6',   catColor: '#6D28D9'    },
  automatisation: { label: 'Automatisation',  section: 'Automatisation',        barColor: '#3B82F6',   catColor: '#2563EB'    },
  reglementation: { label: 'Réglementation',  section: 'Réglementation',        barColor: '#DC2626',   catColor: '#991B1B'    },
  conciergerie:   { label: 'Conciergerie',    section: 'Conciergerie',          barColor: 'var(--gd)', catColor: 'var(--gd)'  },
  fiscalite:      { label: 'Fiscalité',       section: 'Fiscalité',             barColor: 'var(--ol)', catColor: 'var(--ol)'  },
  driing:         { label: 'Driing',          section: 'Driing',                barColor: '#FFD56B',   catColor: 'var(--gd)'  },
}
