// Registre de tous les articles du blog.
// Ajouté automatiquement par scripts/generate-article.mjs pour les nouveaux articles.
export const articles = [
  { slug: 'optimiser-annonce-airbnb',                              categorySlug: 'visibilite',     date: '2025-03-01', readTime: 5,  title: 'Optimiser son annonce Airbnb : les 8 éléments qui font vraiment la différence' },
  { slug: 'tarification-dynamique-lcd',                            categorySlug: 'revenus',        date: '2025-03-01', readTime: 7,  title: 'Tarification dynamique en location courte durée : par où commencer' },
  { slug: 'messages-airbnb-automatiser',                           categorySlug: 'automatisation', date: '2025-03-01', readTime: 4,  title: 'Les 5 messages Airbnb à automatiser absolument dès cette semaine' },
  { slug: 'google-my-business-hotes-lcd',                          categorySlug: 'visibilite',     date: '2025-03-01', readTime: 6,  title: 'Pourquoi Google My Business est indispensable pour les hôtes LCD en 2025' },
  { slug: 'reservation-directe-sans-commission',                   categorySlug: 'revenus',        date: '2025-03-01', readTime: 8,  title: 'Réservation directe sans commission : comment se lancer sans site web' },
  { slug: 'creer-conciergerie-airbnb-2025',                        categorySlug: 'conciergerie',   date: '2025-03-01', readTime: 10, title: 'Créer sa conciergerie Airbnb en 2025 : les étapes essentielles pour démarrer' },
  { slug: 'obtenir-avis-5-etoiles-airbnb',                         categorySlug: 'experience',     date: '2025-03-01', readTime: 5,  title: 'Comment obtenir plus d\'avis 5 étoiles sur Airbnb sans harceler tes voyageurs' },
  { slug: 'location-courte-duree-impots-france',                   categorySlug: 'fiscalite',      date: '2025-03-01', readTime: 9,  title: 'Location courte durée et impôts : ce que tout hôte doit savoir en France' },
  { slug: 'outils-gerer-location-courte-duree-2025',               categorySlug: 'automatisation', date: '2025-03-01', readTime: 6,  title: 'Les 7 outils indispensables pour gérer sa location courte durée en 2025' },
  { slug: 'livret-accueil-digital-hotes-lcd',                      categorySlug: 'experience',     date: '2025-03-01', readTime: 4,  title: 'Livret d\'accueil digital : pourquoi c\'est devenu indispensable pour les hôtes LCD' },
  { slug: 'reglementation-lcd-france-2026',                        categorySlug: 'reglementation', date: '2025-11-01', readTime: 8,  title: 'Réglementation LCD France 2026 : tout ce qui change pour les hôtes' },
  { slug: 'driing-plateforme-vacances-sans-commissions',           categorySlug: 'driing',         date: '2025-03-01', readTime: 6,  title: 'Driing : la plateforme de vacances sans commissions qui change la donne' },
  { slug: 'airbnb-vs-booking-com-location-courte-duree',           categorySlug: 'visibilite',     date: '2026-03-25', readTime: 8,  title: 'Airbnb vs Booking.com : lequel choisir pour ton logement LCD ?' },
  { slug: 'photographier-logement-location-courte-duree-smartphone', categorySlug: 'visibilite',   date: '2026-03-25', readTime: 7,  title: 'Comment photographier son logement LCD soi-même (sans matériel pro)' },
  { slug: 'attirer-teletravailleur-nomade-digital-location-courte-duree', categorySlug: 'revenus', date: '2026-03-25', readTime: 7,  title: 'Télétravail et LCD : comment attirer les nomades digitaux dans ton logement' },
  { slug: 'gerer-mauvais-avis-airbnb-reponse-hote',                categorySlug: 'experience',     date: '2026-03-25', readTime: 6,  title: 'Comment gérer un mauvais avis sur Airbnb sans perdre ton classement' },
  { slug: 'declarer-activite-location-courte-duree-france-demarches', categorySlug: 'reglementation', date: '2026-03-25', readTime: 9, title: 'Déclarer son activité LCD en France : les démarches administratives à connaître' },
  { slug: 'gerer-voyageurs-difficiles-location-courte-duree',      categorySlug: 'experience',     date: '2026-03-25', readTime: 7,  title: 'Voyageurs difficiles en LCD : comment prévenir et gérer les situations problématiques' },
  { slug: 'site-reservation-directe-location-courte-duree',        categorySlug: 'revenus',        date: '2026-03-25', readTime: 8,  title: 'Créer son premier site de réservation directe en LCD : par où commencer' },
  { slug: 'conciergerie-airbnb-faire-appel-choisir',               categorySlug: 'conciergerie',   date: '2026-03-25', readTime: 7,  title: 'Conciergerie Airbnb : faut-il en faire appel à une et comment bien la choisir ?' },
  { slug: 'titre-annonce-airbnb-optimiser-clics-visibilite',       categorySlug: 'visibilite',     date: '2026-03-25', readTime: 6,  title: 'Titre d\'annonce Airbnb : comment écrire un titre qui fait cliquer' },
  { slug: 'tarification-dynamique-pricelabs-wheelhouse-beyond-comparatif', categorySlug: 'revenus', date: '2026-03-25', readTime: 8, title: 'Tarification dynamique en LCD : Pricelabs, Wheelhouse ou Beyond — lequel choisir ?' },
  { slug: 'livret-accueil-digital-creer-location-courte-duree',    categorySlug: 'experience',     date: '2026-03-25', readTime: 7,  title: 'Livret d\'accueil digital : pourquoi c\'est devenu indispensable et comment en créer un' },
  { slug: 'fixer-prix-minimum-airbnb-lcd',                         categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Comment fixer son prix minimum sur Airbnb sans se brader' },
  { slug: 'erreurs-debutant-location-courte-duree-premier-logement', categorySlug: 'revenus',      date: '2026-03-25', readTime: 9,  title: 'Premier logement LCD : les 10 erreurs à éviter quand on se lance' },
  { slug: 'location-directe-pourquoi-saffranchir-plateformes',     categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Location en direct : pourquoi de plus en plus d\'hôtes s\'affranchissent des plateformes' },
  { slug: 'premieres-reservations-directes-sans-audience-site-web', categorySlug: 'revenus',       date: '2026-03-25', readTime: 7,  title: 'Comment obtenir ses premières réservations directes sans audience ni site web' },
  { slug: 'base-voyageurs-fideles-location-directe-durable',       categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Construire une base de voyageurs fidèles : la clé de la location directe durable' },
  { slug: 'fixer-prix-reservation-directe-location-courte-duree',  categorySlug: 'revenus',        date: '2026-03-25', readTime: 6,  title: 'Comment fixer son prix pour la réservation directe : ni trop cher, ni bradé' },
  { slug: 'securiser-paiement-reservation-directe-sans-airbnb',    categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Réservation directe : comment sécuriser le paiement et protéger ton logement sans Airbnb' },
  { slug: 'instagram-hotes-lcd-attirer-voyageurs-reservations-directes', categorySlug: 'visibilite', date: '2026-03-25', readTime: 7, title: 'Instagram pour hôtes LCD : comment attirer des voyageurs directement depuis les réseaux' },
  { slug: 'politique-annulation-location-directe-hote',            categorySlug: 'revenus',        date: '2026-03-25', readTime: 6,  title: 'Gérer les annulations en location directe : quelle politique adopter et comment l\'appliquer' },
  { slug: 'description-logement-convertit-reservation-directe',    categorySlug: 'visibilite',     date: '2026-03-25', readTime: 7,  title: 'Rédiger une description de logement qui convertit en réservation directe' },
  { slug: 'google-my-business-reservations-directes-hotes-lcd',    categorySlug: 'visibilite',     date: '2026-03-25', readTime: 8,  title: 'Google My Business pour hôtes LCD : le levier gratuit qui génère des réservations directes' },
  { slug: 'pms-logiciel-gestion-location-courte-duree-debutant',   categorySlug: 'automatisation', date: '2026-03-25', readTime: 8,  title: 'PMS pour débutant : quel logiciel choisir selon ton profil LCD ?' },
  { slug: 'mesurer-performance-canal-reservation-directe-kpi',     categorySlug: 'revenus',        date: '2026-03-25', readTime: 7,  title: 'Mesurer la performance de ton canal de réservation directe : les chiffres qui comptent vraiment' },
  { slug: 'verification-voyageurs-avant-accepter-reservation-lcd', categorySlug: 'experience',     date: '2026-03-25', readTime: 6,  title: 'Comment vérifier un voyageur avant d\'accepter sa réservation en LCD' },
  { slug: 'gabarits-messages-lcd-hotes-templates',                 categorySlug: 'automatisation', date: '2026-03-25', readTime: 5,  title: 'Gabarits de messages LCD : arrête de réécrire les mêmes messages à chaque voyageur' },
  { slug: 'communaute-lcd-groupes-hotes-entraide-facebook',        categorySlug: 'ressources',     date: '2026-03-25', readTime: 6,  title: 'Communauté LCD : pourquoi les meilleurs hôtes ne travaillent pas seuls' },
  { slug: 'partenaires-lcd-outils-valides-terrain-hotes',          categorySlug: 'ressources',     date: '2026-03-25', readTime: 6,  title: 'Partenaires LCD : pourquoi les outils que tu utilises méritent d\'être validés avant d\'y mettre ton argent' },
  { slug: 'formation-google-my-business-lcd-contenu',              categorySlug: 'visibilite',     date: '2026-03-25', readTime: 5,  title: 'Formation Google My Business pour la LCD : ce qu\'elle contient et pourquoi la suivre' },
  { slug: 'chambres-hotes-plateforme-jason-marinho-ressources',    categorySlug: 'ressources',     date: '2026-03-25', readTime: 6,  title: 'Chambres d\'hôtes : comment la plateforme Jason Marinho t\'aide à développer ton activité' },
  { slug: 'conciergeries-lcd-ressources-plateforme-jason-marinho', categorySlug: 'conciergerie',   date: '2026-03-25', readTime: 6,  title: 'Conciergeries LCD : les ressources de la plateforme qui font gagner du temps à grande échelle' },
  { slug: 'formations-lcd-disponibles-plateforme-jason-marinho',   categorySlug: 'ressources',     date: '2026-03-25', readTime: 5,  title: 'Formations LCD disponibles sur la plateforme : ce que tu peux suivre maintenant et ce qui arrive' },
  { slug: 'pourquoi-creer-compte-plateforme-jason-marinho',        categorySlug: 'ressources',     date: '2026-03-25', readTime: 5,  title: 'Pourquoi créer un compte gratuit sur la plateforme Jason Marinho dès maintenant' },
  { slug: 'checklist-menage-professionnelle-location-courte-duree', categorySlug: 'experience',    date: '2026-03-25', readTime: 6,  title: 'Checklist ménage professionnelle pour hôte LCD (+ gabarit à télécharger)' },
  { slug: 'appel-decouverte-jason-marinho-accompagnement-lcd',     categorySlug: 'ressources',     date: '2026-03-25', readTime: 5,  title: 'L\'appel découverte Jason Marinho : à qui ça s\'adresse et ce qu\'on y fait en 30 minutes' },
  { slug: 'amenager-logement-location-courte-duree-petit-budget',  categorySlug: 'experience',     date: '2026-03-25', readTime: 8,  title: 'Aménager son logement pour la LCD avec un petit budget' },
  { slug: 'booking-com-hotes-location-courte-duree-guide',         categorySlug: 'visibilite',     date: '2026-03-25', readTime: 7,  title: 'Booking.com pour les hôtes LCD : tout ce qu\'il faut savoir avant de s\'inscrire' },
  { slug: 'check-in-location-courte-duree-boite-a-cles-serrure-connectee', categorySlug: 'automatisation', date: '2026-03-25', readTime: 7, title: 'Check-in en LCD : accueil en personne, boîte à clés ou serrure connectée ?' },
  { slug: 'assurance-location-courte-duree-airbnb-couverture',     categorySlug: 'reglementation', date: '2026-03-25', readTime: 8,  title: 'Assurance en location courte durée : ce que couvre vraiment Airbnb (et ce qu\'il ne couvre pas)' },
  { slug: 'basse-saison-location-courte-duree-strategies-reservations', categorySlug: 'revenus',   date: '2026-03-25', readTime: 8,  title: 'Basse saison en LCD : 7 stratégies concrètes pour remplir ton calendrier' },
  { slug: 'tva-location-courte-duree-2026', categorySlug: 'fiscalite', date: '2026-04-24', readTime: 8, title: 'TVA en location courte durée : qui est concerné en 2026 et comment se préparer' },
  { slug: 'dpe-location-courte-duree-obligations-2025-2034', categorySlug: 'reglementation', date: '2026-04-24', readTime: 7, title: 'DPE en location courte durée : ce qui est déjà interdit et l\'horizon 2034 que tu ne peux pas ignorer' },
  { slug: 'algorithme-airbnb-2026-criteres-classement', categorySlug: 'visibilite', date: '2026-04-24', readTime: 8, title: 'Algorithme Airbnb 2026 : les 4 critères qui décident vraiment de ton classement' },
  { slug: 'workation-lcd-logement-equiper-louer-cher-hors-saison', categorySlug: 'revenus', date: '2026-04-24', readTime: 7, title: 'Workation en LCD : les 5 équipements qui te permettent de louer 30 % plus cher hors saison' },
  { slug: 'sejours-longs-lcd-strategie-revenus-basse-saison', categorySlug: 'revenus', date: '2026-04-24', readTime: 7, title: 'Séjours longs en LCD : la stratégie complète pour booster ton taux d\'occupation de 15 % en basse saison' },
  { slug: 'chatgpt-booking-com-impact-hotes-lcd', categorySlug: 'visibilite', date: '2026-04-24', readTime: 7, title: 'Booking.com x ChatGPT : ce que l\'intégration IA change concrètement pour ton annonce' },
  { slug: 'photos-airbnb-computer-vision-ia-optimiser', categorySlug: 'visibilite', date: '2026-04-24', readTime: 7, title: 'Photos Airbnb et Computer Vision : comment l\'IA juge tes images et ce qu\'il faut changer' },
  { slug: 'hospitable-tarification-dynamique-incluse-pms-fin-outils-seuls', categorySlug: 'automatisation', date: '2026-04-24', readTime: 7, title: 'Hospitable intègre la tarification dynamique : la fin des outils de pricing séparés pour les petits hôtes ?' },
  { slug: 'cybevasion-rachetee-holidu-impact-hotes-alternatives', categorySlug: 'revenus', date: '2026-04-24', readTime: 6, title: 'Cybevasion rachetée par Holidu : ce que ça change pour les hôtes et les meilleures alternatives' },
  { slug: 'numero-enregistrement-lcd-20-mai-2026-demarches', categorySlug: 'reglementation', date: '2026-04-24', readTime: 6, title: 'Numéro d\'enregistrement LCD obligatoire dès le 20 mai 2026 : les démarches à faire maintenant' },
  { slug: 'description-airbnb-500-caracteres-convertit-2026', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'Description Airbnb : les 500 premiers caractères qui décident de la réservation' },
  { slug: 'photo-couverture-airbnb-7-criteres-algo-computer-vision', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'Photo de couverture Airbnb : les 7 critères de l\'algo Computer Vision en 2026' },
  { slug: 'mots-cles-titre-annonce-airbnb-eviter-spam-detection', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Titre Airbnb 2026 : 9 mots-clés à éviter qui déclenchent le filtre anti-spam' },
  { slug: 'gmb-questions-reponses-hotes-lcd-optimiser', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Google My Business : la section Questions/Réponses sous-utilisée par 90% des hôtes LCD' },
  { slug: 'statistiques-annonce-airbnb-4-kpis-essentiels', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'Statistiques Airbnb : les 4 KPIs essentiels que les hôtes ignorent' },
  { slug: 'point-mort-lcd-calcul-rentabilite-hote', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Calculer son point mort en location courte durée : la méthode en 4 lignes' },
  { slug: 'frais-menage-airbnb-combien-facturer-2026', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Frais de ménage Airbnb : combien facturer en 2026 sans pénaliser ses réservations' },
  { slug: 'tarif-hebdomadaire-vs-nuitee-quand-preferer', categorySlug: 'revenus', date: '2026-04-25', readTime: 5, title: 'Tarif hebdomadaire vs nuitée : quand préférer chaque modèle (avec calculs)' },
  { slug: 'budget-annuel-hote-lcd-grille-couts', categorySlug: 'revenus', date: '2026-04-25', readTime: 7, title: 'Budget annuel d\'un hôte LCD : la grille de coûts complète pour anticiper' },
  { slug: 'diversifier-revenus-lcd-au-dela-nuitees', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Diversifier ses revenus LCD : 7 sources au-delà du tarif nuitée' },
  { slug: 'marge-nette-par-nuitee-suivi-precis', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Marge nette par nuitée : le seul KPI qui compte vraiment en LCD' },
  { slug: 'serrure-connectee-igloohome-nuki-comparatif-2026', categorySlug: 'automatisation', date: '2026-04-25', readTime: 6, title: 'Serrure connectée LCD : Igloohome vs Nuki vs Master Lock — comparatif 2026' },
  { slug: 'automatiser-caution-swikly-youka-test-terrain', categorySlug: 'automatisation', date: '2026-04-25', readTime: 5, title: 'Automatiser sa caution LCD : SwikLy vs Youka vs solution maison' },
  { slug: 'make-zapier-workflow-airbnb-no-code-debutant', categorySlug: 'automatisation', date: '2026-04-25', readTime: 6, title: 'Make ou Zapier pour Airbnb : automatiser ses flows en no-code' },
  { slug: 'capteurs-iot-lcd-bruit-temperature-utile-ou-pas', categorySlug: 'automatisation', date: '2026-04-25', readTime: 6, title: 'Capteurs IoT pour LCD : bruit, température, ouverture — utile ou gadget ?' },
  { slug: 'messagerie-unifiee-3-plateformes-tester', categorySlug: 'automatisation', date: '2026-04-25', readTime: 5, title: 'Messagerie unifiée Airbnb + Booking + direct : 3 outils à tester en 2026' },
  { slug: 'tva-petit-dejeuner-lcd-seuil-37500-2026-detail', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 6, title: 'TVA et petit-déjeuner en LCD : pourquoi le seuil 37 500 € t\'arrive plus vite que prévu' },
  { slug: 'lmnp-vs-lmp-changement-2026-impact', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 7, title: 'LMNP ou LMP en 2026 : ce qui change pour les hôtes Airbnb français' },
  { slug: 'regime-reel-vs-micro-bic-decision-2026', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 6, title: 'Micro-BIC ou régime réel en LCD : la décision avec calculs en 2026' },
  { slug: 'taxe-sejour-lcd-comment-collecter', categorySlug: 'fiscalite', date: '2026-04-25', readTime: 5, title: 'Taxe de séjour en LCD : comment la collecter sans erreur en 2026' },
  { slug: 'assurance-lcd-5-garanties-indispensables-2026', categorySlug: 'reglementation', date: '2026-04-25', readTime: 6, title: 'Assurance LCD : les 5 garanties indispensables en 2026 (et celles inutiles)' },
  { slug: 'bail-mobilite-vs-courte-duree-differences', categorySlug: 'reglementation', date: '2026-04-25', readTime: 6, title: 'Bail mobilité vs location courte durée : les vraies différences pour un hôte' },
  { slug: 'numero-enregistrement-lcd-obtenir-etapes-pratiques', categorySlug: 'reglementation', date: '2026-04-25', readTime: 5, title: 'Numéro d\'enregistrement LCD : 8 étapes pratiques pour l\'obtenir avant mai 2026' },
  { slug: 'travaux-energetiques-lcd-aides-maprimerenov-2026', categorySlug: 'reglementation', date: '2026-04-25', readTime: 7, title: 'Travaux énergétiques en LCD : MaPrimeRénov 2026 et autres aides pour ton DPE' },
  { slug: 'welcome-bag-lcd-12-idees-marquantes-budget', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Welcome bag LCD : 12 idées qui marquent les voyageurs (avec budget)' },
  { slug: 'check-in-tardif-4-solutions-sans-cles', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Check-in tardif Airbnb : 4 solutions sans clé ni présence physique' },
  { slug: 'communiquer-voyageurs-etrangers-5-regles-multilingue', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Communiquer avec des voyageurs étrangers en LCD : 5 règles qui changent les avis' },
  { slug: 'recuperer-mauvais-avis-airbnb-methode-5-etapes', categorySlug: 'experience', date: '2026-04-25', readTime: 6, title: 'Récupérer un mauvais avis Airbnb : la méthode en 5 étapes pour limiter les dégâts' },
  { slug: 'bruit-reglement-interieur-lcd-efficace', categorySlug: 'experience', date: '2026-04-25', readTime: 5, title: 'Bruit voyageur : le règlement intérieur LCD qui fait baisser les plaintes de 70 %' },
  { slug: 'prospection-conciergerie-trouver-premier-mandat', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 6, title: 'Conciergerie LCD : 7 stratégies pour décrocher ton premier mandat' },
  { slug: 'tarif-conciergerie-lcd-grille-marche-2026', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 5, title: 'Tarif conciergerie LCD 2026 : la grille du marché par zone et prestation' },
  { slug: 'equipe-menage-conciergerie-recruter-fideliser', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 6, title: 'Équipe ménage conciergerie : recruter, former, fidéliser en 2026' },
  { slug: 'contrat-mandat-conciergerie-lcd-modele-clauses', categorySlug: 'conciergerie', date: '2026-04-25', readTime: 6, title: 'Contrat de mandat conciergerie LCD : les 8 clauses indispensables en 2026' },
  { slug: 'outils-gratuits-indispensables-demarrer-lcd-2026', categorySlug: 'ressources', date: '2026-04-25', readTime: 6, title: 'Outils gratuits indispensables pour démarrer en LCD en 2026 : la liste complète' },
  { slug: 'checklist-preparation-logement-avant-1ere-reservation', categorySlug: 'ressources', date: '2026-04-25', readTime: 7, title: 'Checklist préparation logement LCD : 47 points avant ta 1ère réservation' },
  { slug: 'top-7-erreurs-nouveaux-hotes-lcd-eviter', categorySlug: 'ressources', date: '2026-04-25', readTime: 6, title: 'Top 7 des erreurs des nouveaux hôtes LCD (et comment les éviter)' },
  { slug: 'trousse-premier-secours-lcd-equipement-obligatoire', categorySlug: 'ressources', date: '2026-04-25', readTime: 4, title: 'Trousse de premier secours LCD : la liste obligatoire et les bonus à ajouter' },
  { slug: 'inventaire-logement-airbnb-modele-photos', categorySlug: 'ressources', date: '2026-04-25', readTime: 5, title: 'Inventaire logement Airbnb : le modèle photo qui te protège des litiges' },
  { slug: 'guide-fiscal-debutant-hote-airbnb-2026', categorySlug: 'ressources', date: '2026-04-25', readTime: 6, title: 'Guide fiscal débutant 2026 : déclarer ses revenus Airbnb sans erreur' },
  { slug: 'formulaire-fiche-police-lcd-obligatoire', categorySlug: 'ressources', date: '2026-04-25', readTime: 4, title: 'Fiche de police LCD : remplir et conserver le formulaire obligatoire' },
  { slug: 'seo-local-hote-lcd-google-maps-visibilite', categorySlug: 'visibilite', date: '2026-04-25', readTime: 6, title: 'SEO local pour hôte LCD : ressortir sur Google Maps en 2026' },
  { slug: 'instagram-reels-tiktok-lcd-attirer-voyageurs', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Instagram Reels & TikTok pour LCD : 6 formats vidéo qui convertissent' },
  { slug: 'profil-hote-airbnb-bio-photo-confiance', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Profil hôte Airbnb : photo et bio qui inspirent confiance et augmentent les réservations' },
  { slug: 'optimiser-annonce-booking-com-2026-classement', categorySlug: 'visibilite', date: '2026-04-25', readTime: 7, title: 'Optimiser son annonce Booking.com en 2026 : 9 leviers de classement' },
  { slug: 'recherches-voyageurs-airbnb-tendances-emergentes-2026', categorySlug: 'visibilite', date: '2026-04-25', readTime: 5, title: 'Recherches voyageurs Airbnb 2026 : 5 tendances émergentes à capter' },
  { slug: 'saisonnalite-tarif-region-france-lcd-2026', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Saisonnalité LCD par région française : la grille tarifaire 2026' },
  { slug: 'airdna-mode-emploi-hote-lcd-debutant', categorySlug: 'revenus', date: '2026-04-25', readTime: 5, title: 'AirDNA mode d\'emploi : utiliser les data marché pour optimiser ton tarif LCD' },
  { slug: 'last-minute-vs-early-booking-strategie-2026', categorySlug: 'revenus', date: '2026-04-25', readTime: 5, title: 'Last-minute vs early booking : la stratégie de remises temporelles en 2026' },
  { slug: 'refacturer-degat-voyageur-airbnb-procedure', categorySlug: 'revenus', date: '2026-04-25', readTime: 6, title: 'Refacturer un dégât voyageur : procédure Airbnb, Booking et direct (2026)' },
  { slug: 'prix-min-max-airbnb-fourchette-tarifaire', categorySlug: 'revenus', date: '2026-04-25', readTime: 5, title: 'Prix min / prix max Airbnb : la fourchette tarifaire qui maximise ton revenu' },
]

export const CATEGORIES = {
  revenus:        { label: 'Revenus',         section: 'Revenus',               barColor: '#E8A020',   catColor: '#B06010'    },
  visibilite:     { label: 'Visibilité',      section: 'Visibilité',            barColor: 'var(--g)',  catColor: 'var(--g)'   },
  experience:     { label: 'Expérience',      section: 'Expérience voyageur',   barColor: '#D97706',   catColor: '#92400E'    },
  ressources:     { label: 'Ressources',      section: 'Ressources',            barColor: '#8B5CF6',   catColor: '#6D28D9'    },
  automatisation: { label: 'Automatisation',  section: 'Automatisation',        barColor: '#3B82F6',   catColor: '#2563EB'    },
  reglementation: { label: 'Réglementation',  section: 'Réglementation',        barColor: '#DC2626',   catColor: '#991B1B'    },
  conciergerie:   { label: 'Conciergerie',    section: 'Conciergerie',          barColor: 'var(--gd)', catColor: 'var(--gd)'  },
  fiscalite:      { label: 'Fiscalité',       section: 'Fiscalité',             barColor: 'var(--ol)', catColor: 'var(--ol)'  },
  driing:         { label: 'Driing',          section: 'Driing',                barColor: '#FFD56B',   catColor: 'var(--gd)'  },
}
